group_vars/backup-pruner/public.yml, requirements.txt, requirements.yml
This PR makes the following fixes:
1. Moves the backup-pruner variables that were in `host_vars` to `group_vars`.
1. Removes unnecessary `cryptography==1.3.1`.
1. Updates the `ansible-role-security` to use the latest upstream master -- I checked the commit history since the commit we were using, and it is mostly just doc/test fixes & updates, and https://github.com/geerlingguy/ansible-role-security/commit/2abe44e34386f66633dd512d8a286e413c232d3f which adds the optional `security_autoupdate_blacklist`.
1. Updates the `ansible-tarsnap` to use a commit hash rather than a branch since it's an external role.
=> Update requirements and move backup-pruner to group vars.

bootstrap-dedicated.yml, group_vars/postgres/public.yml
This PR contains a fix where the backup directory was erroneously overrode, causing disks to fill early.
It also moves a playbook into the public repo as it did not contain any secrets.
=> Remove extraneous variable override, and add bootstrap template

deploy-all.yml, group_vars/accounting/public.yml, group_vars/all/public.yml, requirements.yml
Adds the playbook that'll run the necessary roles for deploying the [Accounting Automation](https://github.com/open-craft/accounting) service.
See https://github.com/open-craft/ansible-secrets-accounting/pull/1 for actual test instructions.
**Make sure to change to use the `master` branch for the role**.
=> Add playbook for the accounting application.

deploy-all.yml, group_vars/postgres/public.yml, requirements.yml
The https://github.com/ANXS/postgresql role is a little broken, so we'd like to move to some external role from a source we've been already often using.
=> Change postgres role used to geerlingguy.postgresql.

group_vars/all/public.yml
When running on dedicated servers, a swapfile should not be created. 
Testing this pull request requires setting up an unused server and running the dedicated server playbook on it. After running the playbook there should not be any swapfile set up on the server.
**Reviewers**
=> Dedicated servers should not set up a swapfile.

group_vars/rabbitmq/public.yml
This adds a command that checks whether rabbitmq passes the health check. If the connection fails for any other reason, the output won't contain the desired message, the `grep` will fail and an error e-mail will be sent by [sanity-checker](https://github.com/open-craft/ansible-sanity-checker).
=> Add RabbitMQ node health check

group_vars/mysql/public.yml
This sets the variable `mysql_table_open_cache`, since we generally have a very high number of open tables. This may help alleviate some of the performance issues we've been seeing with MySQL lately.
=> Set open table cache size to 200,000 for MySQL

group_vars/accounting/public.yml
Complements https://github.com/open-craft/ansible-mattermost/pull/3 but for the accounting service.
=> Renew the certs after stopping nginx.

deploy-all.yml
Mismatches between using `backup-prune` and `backup-pruner` caused running the backup prune playbook to fail. This makes all occurrences consistent on `backup-pruner`, and the playbook succeeds.
Connected to https://github.com/open-craft/ansible-secrets/pull/21
(https://tasks.opencraft.com/browse/OC-4234)
=> Make name consistent with group vars folder name.

README.md, group_vars/mysql/public.yml, requirements.yml
This Pull Request updates the instructions for setting up a MySQL server, and also updates the required `ansible-role-mysql` to use our fork which now has added support for GTID redundancy.
**JIRA tickets**: OC-3959
**Reviewers**
=> Update instructions for MySQL setup, and version of ansible-role-mysql to use our fork

group_vars/mongodb/public.yml
This PR bumps the version of MongoDB to 3.2.
**Testing:**
1) Checkout to this branch and run [mongodb role](https://github.com/open-craft/ansible-playbooks/blob/02b98f5030343052bf14ee61b2acbec67e00087c/deploy-all.yml#L43) against a fresh server or a VM with Ubuntu 16.04.
=> Bump MongoDB version to 3.2.

deploy-all.yml, group_vars/accounting/public.yml, group_vars/all/public.yml, group_vars/dalite/public.yml, group_vars/load-balancer/public.yml, requirements.yml
The Certbot installation introduced in https://github.com/open-craft/ansible-common-server/pull/15 conflicts with the load-balancer role, so we need to disable it for the load balancers.  We also disable it for the Dalite server, since the corresponding role hasn't been fully migrated yet.
This PR should be merged after the following PRs:
* https://github.com/open-craft/ansible-common-server/pull/15
* https://github.com/open-craft/ansible-dalite/pull/6
* https://github.com/open-craft/ansible-load-balancer/pull/21
* https://github.com/open-craft/ansible-rabbitmq/pull/11
* https://github.com/open-craft/ansible-mattermost/pull/4
* https://github.com/open-craft/ansible-link-shortener/pull/2
* https://github.com/open-craft/ansible-accounting/pull/3
* …
=> Disable Certbot installation for some groups.

requirements.yml
Before merging, the version of the common-server role needs to be reverted to `origin/master`.
=> Add Prometheus node exporter roles to requirements.

deploy-all.yml, group_vars/dalite/public.yml, group_vars/load-balancer/public.yml
As usual, we need to revert the changes to requirements.yml before merging, and update the submodule hash after merging.
=> Move node-exporter role to the end of the play for some servers.

playbooks/roles/node-exporter/templates/nginx-node-exporter.j2
HTTP/2 always uses SSL, so we can only enable it if we want to use SSL.
=> Only enable HTTP/2 when using SSL.

playbooks/roles/ocim/templates/env.j2
After posting on the forum today, I noticed that we probably add this warning to the `.env` file.  I also fixed the quoting while I was there.
I tested this by running
ansible-playbook deploy/playbooks/ocim.yml -l stage --check --diff --start-at-task="Install the configuration/environment file"
from the secrets repo and looking at the diff.
=> Add warning to Ocim's .env files.

playbooks/appserver.yml, playbooks/group_vars/accounting/public.yml, playbooks/group_vars/backup-pruner/public.yml, playbooks/group_vars/chat/public.yml, playbooks/group_vars/dalite/public.yml, playbooks/group_vars/elasticsearch/public.yml, playbooks/group_vars/load-balancer/public.yml, playbooks/group_vars/mongodb/public.yml, playbooks/group_vars/mysql/public.yml, playbooks/group_vars/ocim/public.yml, playbooks/group_vars/postgres/public.yml, playbooks/group_vars/rabbitmq/public.yml, playbooks/group_vars/relay/public.yml, playbooks/roles/common-server/defaults/main.yml, playbooks/roles/common-server/meta/main.yml, playbooks/roles/filebeat/README.md, playbooks/roles/filebeat/defaults/main.yml, playbooks/roles/filebeat/handlers/main.yml, playbooks/roles/filebeat/tasks/main.yml, playbooks/roles/filebeat/templates/elastic.preferences.j2, playbooks/roles/filebeat/templates/filebeat.yml.j2
This adds the initial version of the Filebeat role, afresh.
Note that the config here is a little complex. But in exchange, the actual configuration needed for individual groups of servers is very tiny. Otherwise the diff could be much larger.
=> Add filebeat role.

playbooks/accounting.yml, playbooks/backup-pruner.yml, playbooks/chat.yml, playbooks/dalite.yml, playbooks/elasticsearch.yml, playbooks/group_vars/elasticsearch/public.yml, playbooks/load-balancer.yml, playbooks/mongodb.yml, playbooks/mysql.yml, playbooks/ocim.yml, playbooks/postgres.yml, playbooks/rabbitmq.yml, playbooks/relay.yml, playbooks/roles/common-server/meta/main.yml
When deploying Filebeat to all servers, I noticed I should probably pin the Elastic repo for Elasticsearch servers so they don't upgrade their Elasticsearch service accidentally to the latest version given by the Elastic 6.x apt repo.
Also, in order to run Filebeat alone on all servers without having to comment things out (which could cause issues with missing variables) and without having to use `--start-at-task` all the time (which requires us to eventually cancel the playbook mid-way), I tagged Filebeat with `'filebeat'` and ran `ansible-playbooks -vv deploy/playbooks/deploy-all.yml --tags "filebeat"` and only Filebeat ran on all servers without a problem. I then expanded this idea to every role in `common-server` plus all roles in playbooks.
=> Pin Filebeat's Elastic repo for Elasticsearch servers & tag everything

playbooks/roles/node-exporter/defaults/main.yml
There were multiple problems why Prometheus did not pick up the HTTPS targets, but this is the one that almost cost me my sanity, so it gets its own PR.  I specifically looked for typos in the tag names, multiple times, but I just didn't see it.
=> Fix typo in Consul tag.

playbooks/roles/nginx-proxy/handlers/main.yml
The handler is also needed by the appserver playbook, where the common-server role is not available.
=> Copy nginx reload handler from common-server to nginx-proxy.

playbooks/group_vars/learner-profile-dashboard/public.yml, playbooks/roles/learner-profile-dashboard/templates/lpd-pre-backup.sh, playbooks/roles/learner-profile-dashboard/templates/lpd_settings.py
This PR fixes `lpd-pre-backup.sh` file to enable backups of app logs. It also enhances logs with timestamps and removes single sanity check which called a non-existant file.
The code of this playbook has been used to deploy LPD production.
Squashed from https://github.com/open-craft/ansible-playbooks/commit/140a7482b71534c5eb211a1cb078b0d3f538d236.
=> Fix logging and backup logs for LPD.

.gitmodules, playbooks/group_vars/all/public.yml
This updates Tarsnap to the newest version (1.0.39) as of May 29th, 2018.
I've tested and deployed this on our production and staging servers, and we should use this on new servers going forward.
=> Increment tarsnap version to 1.0.39

playbooks/roles/backup-to-tarsnap/templates/backup.sh
This logs the starting and ending time of backups, because otherwise we can't see how often they run.
Logs are at `/var/log/backup.log`.
To test this, add the commands to a backuped server, wait, and check that log file.
=> Add start and end time to tarsnap logs

playbooks/learner-profile-dashboard.yml, playbooks/roles/dalite/templates/dalite-pre-backup.sh, playbooks/roles/learner-profile-dashboard/templates/lpd-pre-backup.sh
This PR fixes failing `lpd-pre-backup.sh` script.
Changes have been already applied to LPD stage and production.
cf. [OC-4365](https://tasks.opencraft.com/browse/OC-4365)
=> Fix failing pre-backup script for LPD.

playbooks/group_vars/load-balancer/public.yml, playbooks/group_vars/mongodb/public.yml, playbooks/group_vars/mysql/public.yml, playbooks/roles/consul/handlers/main.yml, playbooks/roles/mongodb/defaults/main.yml, playbooks/roles/mongodb/files/mongodb_exporter.service, playbooks/roles/mongodb/meta/main.yml, playbooks/roles/mongodb/tasks/main.yml, playbooks/roles/mysql/defaults/main.yml, playbooks/roles/mysql/meta/main.yml, playbooks/roles/mysql/tasks/main.yml, playbooks/roles/mysql/templates/mysqld_exporter.service.j2
Test instructions:
1. Go to https://prometheus.net.opencraft.hosting/targets. The default username is 'prometheus' and you should have the password.
2. Ensure that the HAProxy, MongoDB, and MySQL exporters show as being healthy targets (not red). (Note: you will see one of the HAProxy ones, haproxy-stage.opencraft.hosting, being red for reasons discussed on the ticket).
3. Go to https://haproxy-stage-3.net.opencraft.hosting:19101/metrics, https://mongodb-stage.opencraft.hosting:19001/metrics, and https://mysql-im-2-slave2.net.opencraft.hosting:19104/metrics. The default username is 'node-exporter' and you should have the password. Let your browser skip verifying the SSL certificate -- it's not provided by a recognized certificate authority.
4. For each of the above, ensure that you see a …
=> Install service-specific exporters.

playbooks/roles/mysql/defaults/main.yml, playbooks/roles/mysql/handlers/main.yml, playbooks/roles/mysql/tasks/main.yml, playbooks/roles/mysql/templates/mysqld_exporter.service.j2
* Should notify for a restart on the service.
* Should use 127.0.0.1 so we can include password in group vars safely.
* For some reason the template seems to not print a newline if
end with {% endif %}.
Does not need review: makes no functional change, and only matches what is currently live.
=> Fix issues with the MySQL exporter.

playbooks/roles/learner-profile-dashboard/templates/lpd_settings.py
This PR adds timestamps to logging in LPD. It had been introduced via https://github.com/open-craft/ansible-playbooks/commit/d103ef658097f92d3b911aaff6b51d0e5f09526e but then was accidentally removed in https://github.com/open-craft/ansible-playbooks/pull/39.
=> Add timestamps to logging in Learner Profile Dashboard app

playbooks/roles/learner-profile-dashboard/templates/lpd_settings.py
cf. [OC-4751](https://tasks.opencraft.com/browse/OC-4751)
**Related PRs**
- https://github.com/open-craft/learner-profile-dashboard/pull/15
- https://github.com/open-craft/ansible-secrets/pull/58
None. This just enables logging for an additional module ([`lpd/client.py`](https://github.com/open-craft/learner-profile-dashboard/blob/master/lpd/client.py)). We previously verified that the playbook puts `templates/lpd_settings.py` in the right place, and that the LPD applies any custom settings that it contains (cf. https://github.com/open-craft/ansible-secrets/pull/54).
**Reviewers**
=> Update logging configuration for LPD.

playbooks/roles/ocim/meta/main.yml
Test instructions:
1. Try starting a fresh Ocim devstack without this and notice it fails.
2. Try it with this and notice it succeeds.
=> Don't install nginx-proxy and tarsnap on Ocim devstack.

playbooks/group_vars/mysql/public.yml
This sets the [`wait_timeout`](https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_wait_timeout) for MySQL servers to 5 minutes, rather than the 8 hours set by default.
The previous setting held open unused MySQL connections for too long and risks exhausting the connection table on MySQL servers.
=> Set mysql wait timeout to reasonable value

playbooks/roles/nomad/tasks/main.yml, playbooks/roles/nomad/templates/nomad.service.j2
We want to run Redis and Memcache on the Nomad cluster, and the easiest way to do so is to install them via apt, and then use the Nomad "exec" driver to spawn the processes.
This PR also makes sure that Nomad clients are run as root, which is required for them to be able to properly launch tasks.
=> Install Redis and Memcache on Nomad clients.

playbooks/roles/curator/defaults/main.yml, playbooks/roles/curator/tasks/main.yml, playbooks/roles/curator/templates/action.yml.j2, playbooks/roles/curator/templates/config.yml.j2
The old cronjob was deleting the Kibana index too because the Kibana index became older than X amount of days. We don't want that, so I created a proper action file now to do the same deletion as before but this time also ignore the Kibana index.
*Test Instructions*:
1. Run `curator_cli show_indices` to see current indices.
1. Change the number of days in `/etc/curator/action.yml` to 2.
1. Run the command `curator --config /etc/curator/config.yml /etc/curator/action.yml` as root manually.
1. Run `curator_cli show_indices` again and ensure only the proper indices are deleted, and Kibana is left intact.
1. **Change back the number of days to the current 5**.
=> Make a curator action file and ignore kibana index.

playbooks/roles/certbot/files/restart-nginx.sh, playbooks/roles/certbot/tasks/main.yml
This PR adds a certbot hook script `restart-nginx.sh` (which reloads the nginx service) to the `/etc/letsencrypt/renewal-hooks/deploy` directory. Verified that nginx uses the renewed certificate by doing a forced renewal with the `--force-renewal` flag and checking the validity of the certificate presented by nginx on connecting to port 19100.
=> Add a certbot hook to restart nginx on deploying renewed certificates

playbooks/roles/mattermail/defaults/main.yml
The mattermail config was incorrect without this. It is now fixed.
=> Add a missing backslash.

playbooks/roles/mattermail/tasks/main.yml
When running the Mattermail role I noticed it always rebuilds the binary. This is because the `githash` value that we register is actually an entire dictionary, where the key/value pairs are not ordered, occasionally causing `githash` to then differ with what is inside of `/opt/mattermail/.hash` due to different order.
According to the [return values of the git module](https://docs.ansible.com/ansible/latest/modules/git_module.html#return-values), we want the `after` value. I used this diff to ensure that it doesn't re-install anymore if using the same commit hash -- and indeed it works out.
=> Use the git hash rather than the full dictionary.

playbooks/roles/appserver/README.md, playbooks/roles/appserver/defaults/main.yml, playbooks/roles/appserver/tasks/main.yml, playbooks/roles/appserver/templates/consul-connect.service.j2, playbooks/roles/consul/templates/config.json.j2
This new role sets up the Consul Connect proxies required to connect to Redis and Memcache on Open edX app servers.  It is meant to be called by Ocim before running the `edx_sandbox.yml` playbook to actually set up Open edX.
For testing instructions, see https://tasks.opencraft.com/browse/OC-4333.
=> Add role to set up Consul Connect proxies on app servers.

playbooks/roles/appserver/defaults/main.yml, playbooks/roles/appserver/tasks/main.yml
Since we are not going to use a highly available Redis deployment in the first iteration, I needed to adapt this role for a single-process Redis deployment.  For testing, it's enough to run the role against some app server.  End-to-end testing will be performed as part of [OC-4334](https://tasks.opencraft.com/browse/OC-4334).
=> Connect to non-replicated Redis deployment without Sentinel.

playbooks/roles/tarsnap/tasks/configure.yml, playbooks/roles/tarsnap/tasks/main.yml
The current version is only configuring tarsnap when the tarsnap key isn't specified or is empty, which is the opposite of what it should be doing.
=> [OC-5141] Invert logic in tarsnap role.

playbooks/roles/mattermail/templates/mattermail.service.j2, playbooks/roles/mattermost/tasks/mattermost.yml, playbooks/roles/mattermost/templates/autolink.json.j2, playbooks/roles/mattermost/templates/mattermost.service.j2
This fixes a few issues with the Mattermost server:
* Mattermail will be killed if it uses too much memory, so it does not take Mattermost down.
* The Mattermost plugin directory is created if it does not exist yet.
* We now use the new `mattermost` binary instead of the deprecated `platform` binary.
* Correcly handle links with a query string in the autolinker.
=> Various fixes for Mattermost and the autolinker.

playbooks/roles/backup-pruner/defaults/main.yml, playbooks/roles/backup-pruner/templates/backup-pruner.sh
This is currently deployed.
Test instructions:
- Check jobs that happened after the start of this PR to ensure that the server did not have memory issues. You can probably use the fact that there are no missed data points as a proxy to determine whether this is working, because it means the node exporter process did not get killed by the kernel to free up memory.
=> Fix issue with backup pruner using too much memory at once.

playbooks/roles/mongodb/defaults/main.yml, playbooks/roles/mongodb/tasks/main.yml, playbooks/roles/mysql/defaults/main.yml
There're two changes this PR is introducing to help achieving [OC-5001](https://tasks.opencraft.com/browse/OC-5001) goals:
- Changing the MongoDB exporter to help us collecting MongoDB query execution time.
- Enable collecting mysql query response time by default.
=> Prometheus exporters

playbooks/hxat-catchpy-loris.yml
The `common-apache2` role that installs the `apache2` package was mistakenly added to all deployments.
This PR restricts this role to HxAT-related deployments, specifically hxat, catchpy and loris.
=> Restrict common-apache2 to hxat-related servers

playbooks/roles/tarsnap/defaults/main.yml, playbooks/roles/tarsnap/tasks/configure.yml
Update tarsnap's cron task to allow minute, hour, day, month and week values. Set default to every hour
=> Allow for more crontab granular control for tarsnap.

.gitmodules, playbooks/elasticstack.yml, playbooks/group_vars/elasticstack/public.yml
Blockstore uses ElasticSearch 6. This is a role to configure a server to act as a dedicated ElasticSearch server. Currently it is not production ready and may need more configuration in the future.
- Uses the official Ansible role for installing Elastic Stack 6.
- ElasticSearch is behind nginx with basic auth configured.
=> Playbook for setting up an Elastic Stack server

playbooks/appserver.yml, playbooks/roles/nginx-proxy/handlers/main.yml, playbooks/roles/nginx-proxy/tasks/main.yml
Due to an ansible bug, when running the appserver.yml playbook, the `reload nginx` handler is skipped when it should not be.
* When the `consul` role runs, its dependent [`nginx-proxy` meta role is skipped](https://github.com/open-craft/ansible-common-secrets) when [`consul_http_password: null` (default value)](https://github.com/open-craft/ansible-playbooks/blob/f3a5bdeb1c4f263716d200609e89dcd8e626f6d4/playbooks/roles/consul/defaults/main.yml#L55). 
The variables in our https://github.com/open-craft/ansible-common-secrets repo do not override this default, because we don't need the `consul` nginx proxy to run on our appservers.
* The `node-exporter` also [depends on the `nginx-proxy` role](https://github.com/open-craft/ansible-playbooks/blob/f3a5bdeb1c4f263716d200609e89dcd8e626f6d4/playbo …
=> SE-617 Force appserver playbook to reload nginx

playbooks/hxat-catchpy-loris.yml, playbooks/roles/catchpy/tasks/main.yml, playbooks/roles/catchpy/templates/catchpy-pre-backup.sh, playbooks/roles/hxat/defaults/main.yml, playbooks/roles/hxat/tasks/main.yml, playbooks/roles/hxat/templates/hxat-pre-backup.sh, playbooks/roles/hxat/templates/secure.py.j2
This upgrades hxat to 1.1.4, which introduces a variable which we can use to disable the keyboard icon shown in this image:
This is a temporary fix until we have other accessibility fixes.
Use together with https://github.com/open-craft/ansible-secrets/pull/99
In addition, it introduces tarsnap backup scripts for hxat's DB and catchpy's DB. No files require backup, just DBs. loris doesn't require backup because we're not using image annotations yet so there aren't user files in the server.
Testing instructions:
For the icon, enter into a lesson that has this LTI component [(example)](https://edge.edx.org/courses/course-v1:MITx+HXAT-MITx+2018/courseware/96e8b28c6a874b9b9afff7b371d4b63d/8db6619a7fe54880a52b8e553bdb8428/2?activate_block_id=block-v1%3AMITx%2BHXAT-MITx%2B2018%2Btype%40vertical% …
=> Update hxat to 1.1.4 and add backups to hxat/catchpy

playbooks/group_vars/load-balancer/public.yml
Test Instructions:
1. Go to logs.opencraft.com
1. Go to the "Discover" page
1. Give search query `type: vault`
1. Ensure logs are showing up
=> [BB-870] Add filebeat config for vault logs.

playbooks/load-balancer.yml
The `caching_resolver_enabled` variable defined in the `load-balancer.yml` took precedence over the `host_vars` variable defined for the host. This PR fixes that issue.
Run
```
ansible-playbook -vvv -C --diff deploy/playbooks/deploy-all.yml  -l "<host/group on which unbound should be installed>" --tags "unbound"
```
and
```
ansible-playbook -vvv -C --diff deploy/playbooks/deploy-all.yml  -l "<host/group on which unbound shouldn't be installed>" --tags "unbound"
```
and verify that result is as expected.
=> [BB-840] Fix precedence issue of 'caching_resolver_enabled' variable

playbooks/load-balancer.yml, playbooks/roles/unbound/tasks/main.yml
Fixes the below warning
```
[WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: "{{ caching_resolver_enabled | default(false) }}"
```
and the warning from the `apt` module that the `installed` state is deprecated and that the `present` state should be used.
=> [BB-840] Fix the when condition to not use jinja2 delimiters and apt module warning

playbooks/roles/learner-profile-dashboard/templates/lpd_settings.py
... to match [recent changes](https://github.com/open-craft/learner-profile-dashboard/pull/17) to defaults in learner-profile-dashboard repo.
Changes have been deployed to [LPD stage](https://lpd-stage.opencraft.hosting/) for verification.
1. SSH into LPD stage via `ssh ubuntu@lpd-stage.opencraft.hosting`. (I added your GitHub key to this instance.)
1. Start watching the new log files via `tail -f /var/log/lpd/default.log /var/log/lpd/django.log /var/log/lpd/security.log`.
1. Navigate to [HGSE stage](https://hgse-stage.opencraft.hosting/) and proceed with the test instructions from https://github.com/open-craft/learner-profile-dashboard/pull/18. Observe that the logs will update as you step through the test instructions for that PR.
* Note that not all of them will …
=> Adjust LPD logging settings

playbooks/roles/common-apache2/templates/certbot-renew.sh
This adds `/usr/sbin` to the PATH of the cron job. That should be enough:
```
root@mit-loris:~# whereis a2ensite certbot service apache2ctl
a2ensite: /usr/sbin/a2ensite /usr/share/man/man8/a2ensite.8.gz
certbot: /usr/bin/certbot
service: /usr/sbin/service /usr/share/man/man8/service.8.gz
apache2ctl: /usr/sbin/apache2ctl /usr/share/man/man8/apache2ctl.8.gz
```
The cron job was running with `PATH=/usr/bin:/bin` and it didn't work before because it couldn't run `a2ensite` and therefore it didn't commute the apache config. 
We also had `certbot` hinting at missing paths.
```
/var/log/letsencrypt/letsencrypt.log:2019-04-18 00:07:27,235:DEBUG:certbot.plugins.util:Can't find apache2ctl, attempting PATH mitigation by adding /usr/sbin:/usr/local/bin:/usr/local/sbin
```
Test:
- experiment with …
=> [SE-954] Add PATH to cron job to renew hxat certificates

playbooks/group_vars/elasticstack/public.yml
Our ElasticSearch (in the ELK server) was suffering with 1 Gb of heap. With 4 Gb it ran fine. The server has 16 Gb.
People mention ([e.g.](https://support.cloudbees.com/hc/en-us/articles/218888897-Elasticsearch-NoShardAvailableActionException)) that 2 Gb isn't enough for big collections; our indices are >280 Gb, and ElasticSearch was hanging in many cases with big queries (e.g. whole-year logs), so I think 4 will work. They even recommend giving half the RAM to Lucene.
If we give too much RAM, less can be used for OS cache. We may have to find the right compromise.
With 4 Gb heap, this is the :
```
root@logs:~# free -m
total        used        free      shared  buff/cache   available
Mem:          15951        6214         181           1        9554        9402
Swap:          1021 …
```
=> Raise JVM heap size to 4 Gb for ElasticSearch

playbooks/roles/learner-profile-dashboard/templates/lpd_settings.py
Cf. [SE-980](https://tasks.opencraft.com/browse/SE-980)
Updates template for `local_settings.py` to include storage settings introduced via https://github.com/open-craft/learner-profile-dashboard/pull/21.
**Related PRs**
* https://github.com/open-craft/learner-profile-dashboard/pull/21
* https://github.com/open-craft/ansible-secrets/pull/118
This PR doesn't make any fundamental changes to the deployment procedure for https://github.com/open-craft/learner-profile-dashboard/, so there is no need to step through a full re-deployment to test them. Just make sure that the names of the three variables introduced here (`LPD_AWS_ACCESS_KEY_ID`, `LPD_AWS_SECRET_ACCESS_KEY`, and `LPD_AWS_STORAGE_BUCKET_NAME`) match those of the variables added to secrets for LPD stage and LPD …
=> Add storage settings for LPD

playbooks/roles/rabbitmq/defaults/main.yml, playbooks/roles/rabbitmq/tasks/main.yml
The erlang-nox packange no longer cleanly installs on Ubuntu 16.04.
This patch switches to esl-erlang which is still working instead.
**Note**:
- This cleanly installs on a system that doesn't have `esl-erlang` or `rabbitmq-server` already installed, but will fail if they are already installed on the server, even if the versions are identical to the ones we're trying to install. The reason is that the "Unlock erlang and rabbitmq" step in the rabbitmq role causes existing installations to get upgraded to latest versions, which in theory should be fine because we downgrade them in the next step ("install rabbitmq"), but `rabbitmq-server` does not downgrade cleanly for some reason. It complains about locks on the mnesia folder. Perhaps a fix is to just stop rabbitMQ server before performing …
=> Fix RabbitMQ dependencies.

playbooks/roles/load-balancer-v2/templates/backend.map.ctmpl, playbooks/roles/load-balancer-v2/templates/haproxy.cfg.ctmpl
The Ocim instance's configuration is being saved as a single K/V value. This PR takes that into consideration and is also backwards compatible to handle multiple k/v pairs for configuration.
There are two templates that use consul values (backend and haproxy config templates).
Given a test consul values of:
```python
[{'CreateIndex': 83,
'Flags': 0,
'Key': 'ocim/instances/1',
'LockIndex': 0,
'ModifyIndex': 83,
'Value': b'{"domain_slug": "instance-slug", "basic_auth": "asdf", "health_checks_enabled": "false", "version": 1, "domain": "locahost.domain", "active_app_servers": [], "name": "instance 1", "domains": ["lms.localhost.domain", "studio.localhost.domain"]}'},
{'CreateIndex': 224,
'Flags': 0,
'Key': 'ocim/instances/2/active_app_servers',
'LockIndex': 0,
'ModifyIndex': 224,
'Value': …
```
=> [BB-1009] Update template to work with single K/V format for config

playbooks/roles/rabbitmq/defaults/main.yml, playbooks/roles/rabbitmq/tasks/main.yml
This PR adds the manual steps for rabbitmq deployment into the ansible playbook. The changes are as follows:
- Set letsencrypt directory owner to rabbitmq
- Add vhost and user
- Download rabbitadmin executable
=> Automate the manual steps for rabbitmq

playbooks/roles/sprints/tasks/main.yml
This fixes [this error](https://github.com/open-craft/ansible-secrets/pull/129#issuecomment-515985480) by replacing module name with the one used before Ansible 2.8.
=> [BB-1247] Change `docker_compose` to `docker_service` for older ansible

playbooks/roles/cert-manager/defaults/main.yml
This is a transitional change. In the short term, it will allow better filtering for the ops@ list.
Later, we might want to change the address to a separate one, once we are monitoring certificate expiration.
Before this PR is merged, we need to run `certbot update_account --email ops+letsencrypt@opencraft.com`.
=> [SE-1328] Append +letsencrypt to account email

playbooks/roles/load-balancer-v2/defaults/main.yml, playbooks/roles/load-balancer-v2/tasks/main.yml, playbooks/roles/load-balancer-v2/templates/haproxy.cfg.ctmpl
This PR adds a few configuration variables to the new load balancers to enable the stats page for each HAProxy server.
Review instructions on https://github.com/open-craft/ansible-common-secrets/pull/14
**Reviewer:**
=> BB-1535: Add configuration to enable HAProxy Stats page

playbooks/roles/load-balancer-v2/templates/backend.map.ctmpl, playbooks/roles/load-balancer-v2/templates/haproxy.cfg.ctmpl
This PR removes support to render old Ocim K/V format for load balancer configuration.
I'm not exactly sure how to provide simple testing instructions for this one, since there are no more old format keys in Consul, so nothing would render.
**Testing instructions:**
1. Deploy these changes on a stage load balancer (I already did this to haproxy-stage-3, so you can use that one for testing).
2. Manually add an old format key to Consul using the file provided in the ticket running:
```
consul kv import @test.json
```
3. Make sure this backend isn't rendered on `/etc/haproxy/backend.map` or `
/etc/haproxy/haproxy.cfg`.
If the files are not being rendered, run these lines:
```
rm /etc/haproxy/backend.map && consul-template -once -config /etc/consul-template/config/backend.map.hcl
rm …
```
=> BB-1534: Remove rendering from old Ocim kv format

playbooks/group_vars/prometheus/public.yml, playbooks/roles/mysql/defaults/main.yml, playbooks/roles/mysql/templates/mysqld_exporter.service.j2, playbooks/roles/prometheus/tasks/grafana.yml
**Testing instructions**
1. Load the [MySQL dashboard](https://prometheus.net.opencraft.hosting:3443/d/6-kPlS7ik/mysql?orgId=1) in Grafana. Note that both replicas are up.
1. ssh to a replica; get a `mysql` shell as root and run `STOP SLAVE;`
1. Observe in Grafana that within a few seconds, the replica is marked down
1. Note that the alert has entered a pending state [in Prometheus](https://prometheus.net.opencraft.hosting/alerts)
1. Wait ten minutes.
1. See that the alert is now firing and ops@ gets an email.
1. Run `START SLAVE;` and see that the alert resolves and dashboard returns to green
There is no easy way to test the lag alert but that's okay. . . we don't get anywhere close to enough to writes for our replicas to fall permanently behind.
=> [SE-1464] Set alerts for MySQL replica status

playbooks/roles/mattermost/defaults/main.yml, playbooks/roles/mattermost/tasks/mattermost.yml
This PR contains the fixes for deploying the mattermost auto-link plugin and was tested in the most-recent upgrade to 5.15.0
* Upgrade Mattermost using the changes in this PR and the corresponding changes in the related ansible secrets PR.
=> [SE-888] Fixes for the mattermost autolink plugin

playbooks/roles/common-server-init/tasks/chkrootkit.yml, playbooks/roles/common-server-init/templates/update-chkrootkit-log
Description
=========
This PR adds a daily cron entry that updates the expected `chkrootkit` output with whatever was the last output.
This results in each change to the output being reported only once to ops.
Testing
----------
1. Deploy this to a VM which runs the chkrootkit daily.
2. If the vm wasn't notifying the chkrootkit diff, make sure to modify the chkrootkit expected log to make it notify.
3. Check there's no difference between the chkrootkit expected and today logs and that the vm stops notifying after one day.
=> BB-1667 Update chkrootkit expected output daily

.gitmodules, playbooks/deploy-all.yml, playbooks/memcached.yml, playbooks/roles/memcached/README.md, playbooks/roles/memcached/tasks/main.yml
This uses https://github.com/geerlingguy/ansible-role-memcached, unmodified. In the end we didn't need to add SASL authentication.
It also adds a companion role called just `memcached` which completes the setup (it just needs to open the port), same as we see in other roles.
Run this from the ansible-secrets repository, and by using the other PR (https://github.com/open-craft/ansible-secrets/pull/143). See the testing instructions there.
=> [SE-1604] Add role to deploy a memcached server

playbooks/roles/ocim/defaults/main.yml, playbooks/roles/ocim/files/venv_exec, playbooks/roles/ocim/meta/main.yml, playbooks/roles/ocim/tasks/common.yml, playbooks/roles/ocim/tasks/main.yml, playbooks/roles/ocim/tasks/vagrant.yml, playbooks/roles/ocim/templates/archived_cleanup.j2, playbooks/roles/ocim/templates/bashrc, playbooks/roles/ocim/templates/venv_exec.j2, playbooks/roles/pyenv/defaults/main.yml, playbooks/roles/pyenv/tasks/main.yml
Adds changes required to deploy a pyenv-based environment for the Ocim Vagrant development environment.
This can be used to test the changes made in https://github.com/open-craft/opencraft/pull/475/files on the vagrant devstack.
=> [BB-1375] Update roles for deploying the pyenv environment

playbooks/roles/common-server-init/tasks/chkrootkit.yml
This fixes the script name for `update-chkrootkit-log`.
1. Deploy any role that contains the `common-server-init` role.
1. Make sure it does not fail when copying the script.
```
$ ansible-playbook -l localhost playbooks/ocim.yml
(...)
TASK [common-server-init : Update expected output daily] ***********************
changed: [localhost]
(...)
```
=> BB-1667 Fix src script

playbooks/roles/load-balancer-v2/templates/haproxy.cfg.ctmpl
These are a few additions to the Consul template which renders the HAProxy configuration from the values which Ocim stores in the `ocim/instances/` prefix.
Specifically, if Ocim sets the IP address to "nil" (this should never happen and yet there were entries like this for the CI tests) the unscheduled-maintenance-page will be used instead, while if there are no active appservers at all, the preliminary-page will be used.
**Testing instructions**
Grep the output of `consul kv get --recurse  ocim/instances | cut -f2- -d: | jq` on haproxy-integration.net.opencraft.hosting to find examples.
Check that those examples are properly rendered in `/etc/haproxy/haproxy.cfg` and that `/usr/sbin/haproxy -c -V -f /etc/haproxy/haproxy.cfg` is happy.
=> Prevent corrupting HAProxy cfg with missing IPs

playbooks/roles/ocim/tasks/vagrant.yml
This PR adds a step to install JS dependencies to the OCIM Vagrant role. This is necessary to run JS tests and was added only to CI.
1. Make sure you have an OCIM devstack that don't have the JS dependencies
2. Run `vagrant provision` with this branch checked out as `/deploy´
3. Inside the Vagrant machine run `make test.js`
4. Make sure the tests complete without errors
Alternatively, destroy the Vagrant box and run `vagrant up` which will reprovision it with the JS dependencies.
=> BB-1796 Install JS dependencies when provisioning Vagrant

playbooks/wordpress.yml
This PR makes sure the `certbot` role runs last when deploying wordpress. This ensures the nginx configurations aren't replaced to the default without SSL.
1. Deploy `wordpress` playbook (already done)
1. Make sure `https` access work correctly
=> BB-1881 Run certbot after wordpress

playbooks/roles/rabbitmq/defaults/main.yml, playbooks/roles/rabbitmq/templates/rabbitmq.config.j2
(disabled by default)
Self explanatory. The reason behind this change is because celery workers don't appear to be sending heartbeats even though negociating a nonzero interval, which causes regular connection resets. :(
1. deploy rabbitmq with this branch
1. verify that the generated rabbitmq.config is valid and sets heartbeat to zero
1. see https://github.com/edx/edx-platform/pull/21567 for a practical test
**Reviewer**:
=> SE-1541 Add option to disable rabbitmq heartbeat

playbooks/roles/pyenv/tasks/main.yml
Python 3.8.0 no longer parses lists in ansible roles properly: Users
were greeted with errors such as:
sre_constants.error: bad character range l-d at position 34
These mysterious errors were not present in the 3.7.x series and below.
Replacing the use of with_items: with loop: fixed the issue and the
playbook proceeded as expected.
Since use of with_* is no longer encouraged by Ansible [1], and the
unexpected behavior was exhibited by using with_items, replacement of
all instances of with_items seems the most reasonable. As with_items is
directly replacable with loop (unlike some of the other with_* items
like with_sequence), only the most ancient of Ansible versions could
run into trouble with the change.
[1] https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#migrati …
=> playbooks: replace deprecated with_items with loop

playbooks/roles/load-balancer-v2/templates/haproxy.cfg.ctmpl
The stats page is only using certificates from certs.pem while the
correct certificate is under /etc/haproxy/certs/
This would result in invalid cert errors.
Fixes SE-2016
=> load-balancer-v2: add certs dir to stats ssl

playbooks/roles/load-balancer-v2/templates/consul-certificates-render.sh
The code to ignore the first line in the output of the consul command
to get the keys was added because there was an empty 'ocim/certs/' key
in the staging environment where this was tested. But the key wasn't
present in the production environment, thereby causing the first
certificate to be ignored. This fix will work in the stage environment
after removing the empty key there.
=> [BB-2052] Fix a bug ignoring the 1st certificate when rendering certificates

playbooks/roles/cert-manager/tasks/main.yml, playbooks/roles/cert-manager/templates/deploy_cert.sh
This is needed because the provisioning is done by the certbot
installed inside the cert-manager's pipenv environment and the renewal
is handled by the systemd timer which uses the system-wide
installation of certbot. This script explicitly navigates to the
cert-manager directory and runs the hook script using 'pipenv run'.
* Deploy the changes in this PR on stage and verify that a well-formed `deploy_cert.sh` script is created under `/usr/local/sbin`.
* Deploy the corresponding changes in the `cert-manager` PR which set the deploy hook to the script added here.
* Restart the `cert-manager` service.
* Verify that for a new instance, the certificate is provisioned without any errors once the DNS record is created and the changes have propagated.
* Run a …
=> [BB-2052] Add a separate deploy hook script for deploying certificates to Consul

playbooks/roles/wordpress/tasks/nginx.yml, playbooks/roles/wordpress/templates/default-nginx.j2, playbooks/roles/wordpress/templates/maintenance-nginx.j2, playbooks/roles/wordpress/templates/wordpress-nginx.j2, playbooks/wordpress.yml
Work in Progress
- As I don't have access to the ansible-secrets repository, I'm not able to test the changes in the wordpress Ansible playbook. I have tested the solution in a separate Nginx webserver, installed from scratch, and it worked.
- TODO: create the corresponding SSL certificates and add them to ansible-secrets
=> [BB-2121] Redirect HTTP requests to HTTPS in Nginx configuration file

README.md
As in the title. A `requirements.yml` was originally used to manage dependencies on third party ansible roles. We've since switched to storing these roles as git submodules. This updates the docs to remove references to the old installation method, and add a warning about what happens if you forget to checkout the submodule roles. 
- check correctness of the readme
**Reviewer**:
=> SE-2437 remove outdated references to requirements.yml

playbooks/roles/cert-manager/tasks/main.yml
The `pipenv` command needs to be passed the 
**JIRA tickets**:  SE-2197
**Dependencies**: https://github.com/open-craft/cert-manager/pull/11
**Merge deadline**: "None"
1. Run the `cert-manager.yml` playbook
2. Verify that the version of `certbot` installed in the `cert-manager` virtualenv is `0.31.0`
**Reviewers**
=> SE-2197: Fix pipenv invocation so that pinned versions are respected

playbooks/roles/ocim/defaults/main.yml, playbooks/roles/ocim/tasks/vagrant.yml, playbooks/roles/pyenv/defaults/main.yml
This PR bumps the python version from 3.6.9 to 3.6.10. This also requires an update to pyenv to the [version](https://github.com/pyenv/pyenv/blob/master/CHANGELOG.md#1216) that supports python 3.6.10.
=> Update python version from 3.6.9 to 3.6.10

playbooks/roles/cert-manager/defaults/main.yml, playbooks/roles/cert-manager/templates/cert-manager.sh
The cert-manager should not request certificate right away when DNS records for an instance are set. Instead it should wait some time for the DNS changes to propagate.
This introduces two delays:
1. Make the script that watches for Ocim instance updates in consul sleep for 2 minutes before running the script which acquires a lock requests new certificates. This sleep is required to give Gandi some time to update the DNS records so that when cert-manager requests the certificates, the DNS records are already in place and working correctly.
2. Pass a `--dns-delay` parameter to cert-manager so that it only requests certificates for domains which have been updated more than that `dns_delay` seconds ago. This delay is required so that when cert-manager is invoked after the 2 minute sleep, it …
=> Introduce cert-manager watch delay.

playbooks/roles/consul/README.md, playbooks/roles/consul/defaults/main.yml, playbooks/roles/consul/tasks/main.yml, playbooks/roles/consul/templates/consul.service.j2, playbooks/roles/consul/templates/run_consul.sh.j2, playbooks/roles/consul/templates/update_consul_config.py.j2
This PR implements the changes to allow automatic generation of consul configuration at service startup time when the `consul_auto_generate_config` flag is set to a truthy value.
* Spawn an EC2 instance and run the sidecar playbook with the `consul_auto_generate_config` flag set to `true` in the `hosts` file.
* Verify that the playbook finishes successfully. Log in to the EC2 instance and verify that the auto-generated consul configuration file, `/etc/consul/config.json` uses the correct public IP address as the value of the `advertise_addr` parameter and that the `node_name` parameter is set to the format `<consul_nodename>-<private IP address separated by - instead .>-<public IP address separated by - . instead of .>`.
- Verify that the systemd service unit …
=> [BB-2278] Implement changes to allow consul auto configuration on AWS

playbooks/roles/consul/defaults/main.yml, playbooks/roles/consul/templates/config.json.j2
This adds `acl_token` to generated Consul agent config.
If we don't have an `acl_master_token`, consul will use the anonymous access (independently of whether there's a master token defined).
Since we want to move to token-based connections, we need to specify the token to use.
Notes:
- there seems to be no problem in having an `acl_token` together with `acl_master_token`. Consul will use the `acl_token` token in operations like `consul kv get -keys /`
- *this PR should be merged after all policies are correctly defined* See the [accompanying PR](https://github.com/open-craft/ansible-secrets/pull/178/files). Otherwise we'd be asking servers to use policies that don't exist or that aren't complete
Testing:
- apply it with ansible, or check that the ansible code is in the right place
- …
=> [SE-2530]+[SE-2435] Add Consul ACL tokens to config

playbooks/group_vars/ocim/public.yml
This allows the Ocim app's virtual host name and the hostname of the VM running the app to be different. `CERTBOT_DOMAIN_NAME` will now use the default of `inventory_hostname` which works correctly with the `node-exporter` virtual host and the `ocim` virtual host.
=> [BB-2329] Remove the assumption that ocim domain name is always the same as the hostname

playbooks/roles/load-balancer-v2/templates/haproxy.cfg.ctmpl
When no appservers are active, instance LMS and Studio URLs should not redirect the user, but just display contents of default.opencraft.com. Have applied the patch manually to the below instance on stage too, for testing purposes.
**JIRA tickets**: [SE-2948](https://tasks.opencraft.com/browse/SE-2948)
**Sandbox URL**: https://sid-test-2.stage.opencraft.hosting (The DNS has 3 IP addresses, so you might see the old deployment on IPs other than 54.36.101.120)
1. Run `curl --insecure -v --header "Host:se-2870-test.opencraft.hosting" https://54.36.101.120` and verify 301 Moved Permanently response.
2. Run `curl --insecure -v --header "Host:sid-test-2.stage.opencraft.hosting" https://54.36.101.120` and verify 200 OK is returned, with content of default.opencraft.com …
=> [SE-2948] Remove redirect to preliminary page

playbooks/roles/load-balancer-v2/tasks/main.yml
Some tasks had to be moved around:
1. Directories under `/etc` need to be created early, before the first task that depends on them
2. The `maintenance.yml` tasks need to run before the tasks from the certbot role. The cerbot role needs a running haproxy (to proxy requests to local nginx), but haproxy won't start if the `maint.map` file created by `maintenance.yml` doesn't exist.
**Testing**:
I don't see any way to properly test this without running it on a fresh server, which is a lot of trouble :/ Since the changes are minor (just changing the order of the tasks), I suppose we could skip a full manual test.
**Reviewers**:
=> Fix issues with the load-balancer-v2 role

playbooks/roles/node-exporter/tasks/main.yml, playbooks/roles/sprints/tasks/main.yml
This PR explicitly enables node-exporter during provisioning. It fixes an issue where sometimes node-exporter is active but not enabled and hence doesn't restart automatically on reboot.
**JIRA tickets**: 
**Discussions**: 
**Screenshots**: 
**Sandbox URL**: 
**Merge deadline**: None
1. Setup a virtualenv and install all requirements
2. Create a fresh ubuntu 16.04 vagrant box
3. Run any provisioning script (such as sprints.yml) through ansible
4. Use 'vagrant ssh' and 'systemctl status nodeexporter' to confirm node-exporter is working
5. Use 'vagrant reload'
6. Use 'vagrant ssh' and 'systemctl status nodeexporter' to confirm node-exporter is working
1. I believe this should fix the problem, and i tried …
=> [BB-1716] Enable node-exporter explicitly

playbooks/roles/cert-manager/defaults/main.yml, playbooks/roles/cert-manager/templates/cert-manager.sh
This PR enables using the `--failure-alert-email` option added to `cert-manager` in https://github.com/open-craft/cert-manager/pull/15.
* Deploy the changes in this PR branch on a `cert-manager` instance with `cert_manager_alert_email` set to a valid email address using Ansible variable overrides.
* Verify that the `--failure-alert-email` option is passed correctly to `cert-manager` in the generated `cert-manager.sh` script
* Verify that the `cert-manager` sends an email to the configured address when there is a certificate provisioning failure (already verified in https://github.com/open-craft/cert-manager/pull/15).
* Verify that a proper, working `cert-manager` command without this option is generated in the `cert-manager.sh` script when the default value for …
=> [BB-2231] Allow configuring a failure alert email address for cert-manager

.gitmodules, playbooks/group_vars/prometheus/public.yml, playbooks/ocim.yml, playbooks/roles/redis-exporter/README.md, playbooks/roles/redis-exporter/defaults/main.yml, playbooks/roles/redis-exporter/handlers/main.yml, playbooks/roles/redis-exporter/meta/main.yml, playbooks/roles/redis-exporter/tasks/main.yml
Adds a new ``redis-exporter`` role to send ``redis`` metrics to ``prometheus``. It uses [prometheus_redis_exporter_role](https://github.com/idealista/prometheus_redis_exporter_role) as dependency and adds nginx & consul configurations to work with Ocim infrastructure.
=> [BB-2851] Huey queue monitor

playbooks/roles/load-balancer-v2/templates/backend.map.ctmpl, playbooks/roles/load-balancer-v2/templates/haproxy.cfg.ctmpl, playbooks/roles/load-balancer-v2/templates/nginx-maintenance.conf
This PR fixes the wrong maintenance page issue during scheduled or unscheduled maintenance and during provisioning.
**JIRA tickets**: https://tasks.opencraft.com/browse/BB-3018
~~**Discussions**:~~
~~**Screenshots**: ~~
~~**Sandbox URL**:~~
**Merge deadline**: "None"
1. Move an instance to maintenance mode, proper maintenance page should show
2. Provisioning page should show from local Nginx instead of using external server IP
~~**Author notes and concerns**:~~
**Reviewers**
~~**Settings**~~
=> [BB-3018] Load balancers should serve the maintenance pages from the local nginx vhosts and not redirect to external domains

playbooks/roles/newrelic_infra/README.md, playbooks/roles/newrelic_infra/defaults/main.yml, playbooks/roles/newrelic_infra/tasks/main.yml, playbooks/roles/newrelic_infra/templates/newrelic-infra.yml.j2, playbooks/roles/rabbitmq/defaults/main.yml, playbooks/roles/rabbitmq/meta/main.yml, playbooks/roles/rabbitmq/tasks/main.yml, playbooks/roles/rabbitmq/templates/rabbitmq-config-newrelic-infra.yml.j2
This adds support for newrelic infrastructure plugin with the rabbitmq integration running on rabbitmq instances.  It should allow us to collect metrics on rabbitmq, and use those metrics for alerting (for example, if queue lengths go through the roof).
It also fixes some issues with running the playbook.
- deploy rabbitmq and verify that it completes successfully
- check newrelic and verify that it is receiving metrics from the rabbitmq instance
=> SE-3328 Add newrelic infra and rabbit integration

playbooks/roles/rabbitmq/meta/main.yml
This allows using the `rabbitmq-newrelic` tag to run all newrelic
related tasks for rabbtimq hosts.  Just for convenience.
- run the playbook against a rabbitmq server with the `rabbitmq-newrelic` tag (in some test mode if possible), and verify that the dependency is run also.
**Reviewers**:
=> SE-3328 Tag the newrelic_infra dependency

playbooks/roles/mysql/README.md, playbooks/roles/mysql/defaults/main.yml
It's not used anywhere in the playbook.
**Reviewers**:
=> [SE-3417] Remove unused MYSQL_OPENSTACK_DB_DEVICE variable.

playbooks/group_vars/mongodb/public.yml
Description
=========
This PR removes a dangling configuration that sets the MongoDB engine to mmapv1, which is not what we want and shouldn't be set here.
Testing
======
Check related https://github.com/open-craft/ansible-secrets/pull/219
=> BB-3167 Remove mmapv1 engine configuration

playbooks/hxat-catchpy-loris.yml, playbooks/roles/common-apache2/files/certbot-renew.sh, playbooks/roles/common-apache2/tasks/main.yml, playbooks/roles/common-apache2/templates/certbot-renew.sh
This port the relevant parts from the [certbot role](https://github.com/open-craft/ansible-playbooks/tree/master/playbooks/roles/certbot) to `common-apache2`.
The most important part is upgrading certbot to the version provided as a snap package, which we also use on the rest of our servers, since the PPA installation method is no longer supported upstream and the version in the PPA is outdated.
This was deployed to the three servers that use this role:
- mit-catchpy.opencraft.hosting
- mit-hxat.opencraft.hosting
- mit-loris.opencraft.hosting
The first of the certificates will be up for renewal in about two weeks, so to verify that the renewal process is actually working we'll have to wait.
In order to review this PR, I think it's enough to read through the code make …
=> [SE-3417] Use certbot from snap in common-apache2 role.

playbooks/roles/backup-pruner/tasks/main.yml
The /var/cache folder already exist on Ubuntu (and most other linux distributions), so there's no need to create it in the backup-pruner playbook. In fact forcing `0700` permissions (which is stricter than the default) leads to some periodic system tasks failing.
**Testing**:
This is a trivial change and testing shouldn't be necessary.
=> backup-pruner: don't modify /var/cache permissions

playbooks/roles/mattermost/tasks/mattermost.yml
For BB-3262: Added ansible task to cleanup old mattermost installer files from /tmp after updating.
**Merge deadline**: None
1. Make copies of mattermost installer files in /tmp and change file names or redownload. The ansible task saves the 2 most recent versions of the autolink and teams installers, so there must be 3+ of each in the folder to test cleanup.
2. Run playbook with "--tags cleanup_tmp" and check that only the 2 most recent versions of each installer remains in /tmp. Check that disk space is at an acceptable level (i.e. around 50% usage).
3. Run playbook again without any extra installer files in /tmp to cleanup. Make sure that no errors are thrown.
**Reviewers**
=> [BB-3262] Add cleanup tmp task and tag

playbooks/roles/rabbitmq/defaults/main.yml
RabbitMQ has to be configured with Let's Encrypt's fullchain.pem CA chaing to properly server the intermediate certificates.
Changing the `RABBITMQ_CA_CERTIFICATE_FILE` variable has the effect of changing two lines in `/etc/rabbitmq/rabbitmq.config`:
- [line 1](https://github.com/open-craft/ansible-playbooks/blob/dd5be37e7ba2fd25a0b24959f7b3da8d34380395/playbooks/roles/rabbitmq/templates/rabbitmq.config.j2#L7)
- [line 2](https://github.com/open-craft/ansible-playbooks/blob/dd5be37e7ba2fd25a0b24959f7b3da8d34380395/playbooks/roles/rabbitmq/templates/rabbitmq.config.j2#L18)
The changes were already manually applied on RabbitMQ stage and production.
=> Replace RabbitMQ CA cert file chain.pem -> fullchain.pem.

playbooks/roles/load-balancer-v2/tasks/main.yml, playbooks/roles/load-balancer-v2/templates/backend.map.ctmpl
While working on adding m* client custom redirects, I found 2 bugs in the consul-template implementation:
1. Custom backends were rendered after Ocim ones, meaning that was not possible to override a given domain to point to a different backend (first one in the file is the one that counts). Fixed by: https://github.com/open-craft/ansible-playbooks/commit/86934facee094309c6b4211e0eb0a1af5fb04787
2. The custom domain-backend mapping was being incorrectly rendered, resulting in a giant line effectively ignored by `haproxy` (none of the current custom backends are working). Fixed by: https://github.com/open-craft/ansible-playbooks/commit/d48989c9ca462fa25994d3c6c3a77ada202ae26a
To test this, I've used the m* client domain:
Check `/etc/haproxy/backend.map` you'll see the first entry is 
``` …
```
=> BB-3716: Custom backends take precedence

requirements_ansible_2.8.17.txt
Including separate requirements file, similar to https://github.com/open-craft/ansible-playbooks/blob/master/requirements.txt, but with Ansible 2.8.17, which is required to run playbooks against Ubuntu 20.04.
**JIRA tickets**:
- [BB-3686](https://tasks.opencraft.com/browse/BB-3686)
**Dependencies**:
- https://github.com/open-craft/opencraft/pull/713 depends on this PR.
Look https://github.com/open-craft/opencraft/pull/713.
**Reviewers**
=> [BB-3686] Create separate requirements file for Ansible 2.8.17

playbooks/roles/cert-manager/tasks/main.yml
After the OVH server fire, we had to move the stage certificate manager to a new region.
However, when trying to run the playbook, it failed due to python 3.5.
This fixes that.
* **Jira Tickets**: SE-4243
* Run the playbook on the stage certificate manager
=> Updates cert-manager playbook to use Python 3.6

playbooks/roles/matomo/templates/docker-compose.yml.j2
This PR upgrades matomo from v3 to v4.2.
**JIRA tickets**: https://tasks.opencraft.com/browse/BB-3809
~~**Discussions**:~~
~~**Screenshots**:~~
~~**Sandbox URL**:~~
**Merge deadline**: None
TBD
1. There might be some manual process to be done for database migration.
**Reviewers**
=> [BB-3809] Upgrade matomo from v3 to v4.2

playbooks/roles/discourse/templates/app.yml.j2
This merge request is about adding the MaxMind license key to the Discourse configuration file.
https://github.com/open-craft/ansible-secrets/pull/253
**Jira tickets**
- [FAL-1676](https://tasks.opencraft.com/browse/FAL-1676)
**Testing instructions**
- Connect to [forum.opencraft.com](https://forum.opencraft.com)
- Go to the admin page
- Then "Users"
- Click on a random user
- Click on "IP lookup"
- Check that the IP location is found
- Do the same thing for [edxchange.opencraft.com](https://edxchange.opencraft.com)
**Reviewers**
- @swalladge
=> [FAL-1676] Add MaxMind license key for the forums

requirements_ansible_2.8.17.txt
The `filebeat` role requires a minimum version of `jinja2` in order to complete, due to the particular invocation of the `indent` filter.  Only tested this on the newer Ansible though.
Test instructions:
1.
=> [FAL-1667] Pin jinja2 to a version that works with filebeat

playbooks/roles/elasticsearch/defaults/main.yml, playbooks/roles/elasticsearch/tasks/main.yml, playbooks/roles/elasticsearch/templates/50-extra-jvm.options.j2
[FAL-1773](https://tasks.opencraft.com/browse/FAL-1773)
This allows overriding JVM options for elasticsearch, using the new jvm.options.d directory structure. See https://www.elastic.co/guide/en/elasticsearch/reference/current/jvm-options.html for syntax and more information.
It's not conditionally templated out, because empty files appear to be valid and old elasticsearch versions will just ignore these files.
- set a value for `elasticsearch_extra_jvm_options`
- run this playbook
- verify that /etc/elasticsearch/jvm.options.d/50-extra-jvm.options is created successfully with the expected content
**Reviewers**:
=> FAL-1773 Support custom jvm options for elasticsearch

playbooks/roles/crafty-bot/files/deploy.sh
At the moment, crafty bot does not recreate the celerybeat container. This means that the code running there does not get updated on the server. To fix this issue, we recreate the container just as we do with the django or celeryworker containers.
**Sandbox URL**: N/A
**Merge deadline**: ASAP
1. Run the playbook for crafty-bot by executing `ansible-playbook -u ubuntu -i hosts deploy/playbooks/crafty-bot.yml -l crafty-bot --extra-vars @group_vars/all/public.yml --extra-vars  @group_vars/prod/public.yml` from the secrets repo after updating the deploy submodule
N/A
**Reviewers**
=> [SE-4290] Restart celerybeat container for crafty-bot

playbooks/roles/elasticsearch/README.md
This PR adds documentation around generating certificates for Elasticsearch in order to setup security to prevent confusion or difficulties when setting up new ELK or Elasticsearch services using our playbooks.
**JIRA tickets**: BB-2836
**Merge deadline**: "None"
**Reviewers**
=> Add documentation for generating ElasticSearch SSL certificates

playbooks/roles/prometheus/tasks/main.yml
The default nofile limit for prometheus is quite low, and the upstream change with the fix comes with a lot of other changes that we can't apply right now.
This will override the prometheus systemd unit to apply this limit without editing the existing file.
=> Update prometheus role to increase nofile limit for service

playbooks/deploy-all.yml, playbooks/mailing-list.yml
[FAL-1750](https://tasks.opencraft.com/browse/FAL-1750)
This adds a playbook for mailing list tasks.  We'll need to add to this later when we set up mailman 3, etc.
See https://github.com/open-craft/ansible-secrets/pull/267
Basically, this should set up the common server role on the new mailing list server.
**Reviewers**:
=> FAL-1750 Add playbook for mailing list host

playbooks/roles/common-server-init/tasks/misc.yml, playbooks/roles/common-server/defaults/main.yml
This installs our custom repository and key by default.
For the moment, the repository only includes an updated chkrootkit for xenial, which fixes the periodical MongoDB DoS issue identified in SE-4147.  See https://github.com/open-craft/chkrootkit/pull/1 for the actual change.
=> [SE-4181] Install the Opencraft deb repository

.gitmodules, playbooks/deploy-all.yml, playbooks/group_vars/redis/public.yml, playbooks/redis.yml, playbooks/roles/redis/README.md, playbooks/roles/redis/defaults/main.yml, playbooks/roles/redis/files/redis-backup, playbooks/roles/redis/tasks/main.yml
This PR moves the Redis role variables to common secrets, as we cannot set them by the `ansible-playbooks` repo's default's and we need to apply these variables to all Redis nodes.
**JIRA tickets**: https://tasks.opencraft.com/browse/FAL-2029
**Dependencies**:
* https://github.com/open-craft/ansible-playbooks/pull/229
**Merge deadline**: None
* Proofread as the node already provisioned
-- or --
* Run `terraform destroy` and `terraform apply` using the instructions in `https://gitlab.com/opencraft/dev/ocim-legacy-infrastructure/-/merge_requests/1`
* Check out https://github.com/open-craft/ansible-secrets/pull/283
* Update submodules to use https://github.com/open-craft/ansible-common-secrets/pull/27 and https://github.com/open-craft/ansible-playbooks/pull/229
* …
=> [SE-4567] add clustered redis

playbooks/roles/sanity-checker/files/sanity_check.py
This adds special partitions (like the case in the MySQL Servers hosted in SoYouStart with the `mysql` partition name, but mounted for `/var/lib/mysql`) to be checked by the sanity checks
=> [FAL-1995]: adds partition check for mounted /var

playbooks/roles/mail/defaults/main.yml, playbooks/roles/mail/tasks/main.yml, playbooks/roles/mail/templates/postfix-main.cf.j2, playbooks/roles/postfix/templates/main.cf
[FAL-2014](https://tasks.opencraft.com/browse/FAL-2014)
Also fix some minor typos and wording for the relay server postfix config
- this has been deployed to the relay and new mail server for testing
- check for correctness (new smtpd config should make sense)
**Reviewers**:
=> FAL-2014 Enable smtpd tls for mail server

playbooks/roles/common-server-init/tasks/misc.yml
Based on the documentation and implementation, it seems that the cache is updated if and only if the deadline set by `cache_valid_time` is in the past. Meaning that if we set both `cache_valid_time` and `update_cache` it won't be updated.
Although the changes that were intended to update the cache were added ~3 years ago, we never needed to update keys before – I guess. That's the reason why it did not break before. After the new changes were introduced lately to add the Opencraft repository, we started to face the issue.
To validate the idea, I just removed the `cache_valid_time` parameter from the task and it works nicely.
=> [SE-4582] remove cache_valid_time to update cache

playbooks/redis.yml
Wasn't able to override this with the host vars with this in the playbook vars.
See https://github.com/open-craft/ansible-secrets/pull/290 for test instructions.
**Reviewer**
=> fix: remove redis_slave: !!null from playbook

playbooks/roles/common-server-init/tasks/networking.yml, playbooks/roles/common-server-init/templates/netplan/floating-ip.yaml
This PR replaces `networking` for `netplan` configuration and makes this playbook compatible with Ubuntu 20.04.
I don't want to keep multiple release version handling for simplicity, so this should only be merged once we have the bare-metal servers on Focal.
**Testing instructions:**
I've already applied this playbook on our spare baremetal server.
1. SSH into the server using the DNS record, IP, and failover IP address.
2. Check the network configuration with `ifconfig`.
**Notes:**
Since there's some secrets involved in testing this, I'll leave a comment in the internal ticket.
**Reviewers:**
=> BB-4426: Replace networking with netplan configuration WIP

playbooks/group_vars/prometheus/public.yml
This fixes the error message of `haproxy_frontend_request_errors_high` which seems to have been copy-pasted from `haproxy_backend_response_time_high` and never properly updated.
1. Log into https://prometheus.net.opencraft.hosting/alerts
2. Click on `haproxy_frontend_request_errors_high` and verify that the summary and description templates looks correct.
=> Fix copy-pasted description of prometheus alert.

playbooks/group_vars/prometheus/public.yml
This makes the prometheus query that we use for the frontend error alert more predictable since it uses 5 minute rates instead of the plain accumulative request and error counts.
We're currently querying `haproxy_frontend_request_errors_total / haproxy_frontend_http_requests_total` but both of these variables are cumulative. The number of both of these variables keeps growing more or less monotonically until it is reset when the node exporter flushes its internal value.
This doesn't produce very reliable results, especially around the times when values get flushed.
This PR switches to using a 5 minute rate using the ratio of the rates of these two variables. It also limits the query to the `fe_https` backend only. There are two other backends: `stats`, which is internal only and has a …
=> Update HAProxy frontend error alert condition.

playbooks/roles/common-server-init/defaults/main.yml, playbooks/roles/common-server-init/tasks/misc.yml, playbooks/roles/common-server-init/templates/tmpreaper.conf
In the process, refactor tmpreaper config tasks to use a template,
because we can no longer neatly use the lineinfile method.
- run this playbook against ocim stage and verify the new task shows as unchanged (this has already been run on ocim stage) - note that ocim stage is now running focal, so you'll need the ansible 2.8 requirements set.
- ssh into ocim stage and check that /etc/tmpreaper.conf is as expected and has the expected runtime limit override
- verify that we aren't getting pinged on ops about `error: run time exceeded!` for tmpreaper on ocim stage
**Reviewers**:
=> FAL-2085 Increase tmpreaper runtime limit by default

playbooks/group_vars/elasticsearch/public.yml, playbooks/roles/elasticsearch/defaults/main.yml, playbooks/roles/elasticsearch/tasks/main.yml
This PR fixes issues installing Elasticsearch v1.5 in Ubuntu 20.04 vms.
https://tasks.opencraft.com/browse/BB-4495
- Pull this PR
- Provision a Ubuntu 20.04 VM with the `elasticsearch.yml` playbook.
ASAP
**Reviewer**
=> [BB-4495] Fix the services VM elasticsearch installation issue in our ansible-playbooks repo

playbooks/roles/common-server-init/tasks/misc.yml, playbooks/roles/common-server/defaults/main.yml
This change prioritizes using the opencraft repository for the chkrootkit package. This way future updates to the main release wouldn't prioritize the main release over the opencraft one.
=> [SE-4608] set apt preferences to  prioritize the opencraft repository

playbooks/roles/mail/templates/mailman3-nginx-proxy.conf.j2
[FAL-2284](https://tasks.opencraft.com/browse/FAL-2284)
Only the common-server should listen on port 80,
because it uses that to intercept requests to the well-known acme-challenge location
for certbot renewals.
This server block was blocking certbot renewals by sending the acme-challenge
requests to mailman, instead of letting the common-server server block handle it.
By removing this server block, we fix certbot renewals on the mail server instance.
- verify that certbot renews successfully on mail.opencraft.com (this will not be possible for a few days, unless you run a force renewal, because the certs were renewed today)
- alternatively, run `curl mail.opencraft.com/.well-known/acme-challenge/test` and verify you get a 404, instead of a redirect to https://...
- …
=> FAL-2284 Remove listen on port 80 for mailman3 nginx proxy

playbooks/roles/sanity-checker/tasks/main.yml
[FAL-2311](https://tasks.opencraft.com/browse/FAL-2311)
Previously, it was _supposed_ to run every 10 minutes,
but it skipped '0', so there was a 20min gap every hour,
which can cause false positives for snitches.
Also don't use the `*/10` syntax,
because we want to offset it by one minute,
to avoid issues where everything happens on a minute divisible by 10.
- run this on a server that has the sanity checker configured
- wait an hour
- verify that it runs every 10 minutes, starting at 1 minute past the hour
**Reviewers**:
=> FAL-2311 Run the sanity checker every 10 minutes

playbooks/roles/pyenv/tasks/main.yml
The previous implementation used the loop keyword which installed the
provided packages one at a time and hence was inefficient.
=> [BB-4567] fix: pass the apt packages list directly to the apt module

playbooks/roles/mail/templates/mailman3-nginx-proxy.conf.j2
The default size (1M) was causing lots of 413 errors.
I thought about making this configurable, but we're not resuing this role, so we can keep 10M as a default value for now.
=> fix: increase nginx max_body_size for mailman [BB-4955]

playbooks/roles/filebeat/defaults/main.yml, playbooks/roles/filebeat/templates/filebeat.yml.j2
Rename `prospectors` to `inputs`.
`prospectors` was deprecated in version 6.3, and removed in a later version,
so we can rename without breaking any hosts now (all seem to be 6.8 or 7.*).
Remove `registry_file`.
This was a backwards incompatible change somewhere between version 6.8 and 7.15.
We aren't overriding the default anywhere, so we can simply remove the option altogether.
- deploy [this ansible task](https://github.com/open-craft/ansible-playbooks/blob/5415bde549f04c2a182a0ab6115f939a9b54f945/playbooks/roles/filebeat/tasks/main.yml#L36-L40) to an instance that uses filebeat (eg. logs.opencraft.com; this patch has already been used to deploy there)
- verify that filebeat runs successfully
- verify the filebeat config file looks as expected …
=> FAL-1993 Update filebeat configuration for version 7

README.md
We don't have plans on using features that ZFS provides, so we're not going to set it up on new MySQL servers.
=> [BB-4743] Remove information about ZFS

.gitmodules
This PR fixes the MySQL playbook GitHub URL. Upstream does not contain the commit hash required by Ocim.
```
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
cmdline: git reset --hard 03358d3f180b2e6ffa2a5084f794e09f71884de5 --
stderr: 'fatal: Could not parse object '03358d3f180b2e6ffa2a5084f794e09f71884de5'.'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/var/www/opencraft/instance/models/openedx_appserver.py", line 640, in provision
return self._do_provision()
File "/var/www/opencraft/instance/models/openedx_appserver.py", line 687, in _do_provision
raise ProvisioningError("AppServer deploy failed: unhandled exception") from ex
instance.models.openedx_appserver.ProvisioningError: AppServer deploy failed: …
```
=> fix: revert mysql playbook url

playbooks/roles/postgres/tasks/main.yml
The condition for checking if the `POSTGRES_OPENSTACK_DB_DEVICE` is not working with ansible `2.8.17` as expected. We need to use `when: POSTGRES_OPENSTACK_DB_DEVICE != None` instead of `when: POSTGRES_OPENSTACK_DB_DEVICE`.
=> fix: ensure postgres volume condition is correct

playbooks/group_vars/prometheus/public.yml
Description
This PR add new alert rules for updated node exporter as the new node exporter versions use slightly different metric names
Supporting information
[ticket|https://tasks.opencraft.com/browse/SE-5324]
Dependencies
N/A
Screenshots
N/A
Testing instructions
I already manually add new alert rules config file on prometheus server you can find the new alerts in the prometheus alerts tab, I tested that each alert fire successfully on an appserver that has updated node exporter
Deadline
N/A
=> [SE-5324] new alert rules for updated node exporter

playbooks/roles/docker-compose/tasks/main.yml
Version [`1.26.0`](https://docs.docker.com/compose/release-notes/#1260) started using `python-dotenv` for processing `.env` files, which made parsing quotes consistent.
To test SprinCraft, I've done the following checks:
1. Logged into the Django shell and verified that env variables surrounded with quotes (because they contain spaces) do not contain these quotes in their parsed versions, i.e. that `GOOGLE_ROTATIONS_RANGE="Rotation Schedule"` is parsed to `Rotation Schedule`, instead of `"Rotation Schedule"`.
We could consider upgrading to [v2](https://github.com/docker/compose), but last time I've checked (in November), it didn't work well with Ansible's `compose` module. It might be fixed now, but we're using an older version of Ansible, so we would need to use something like this …
=> chore: update docker-compose from `1.24.0` to `1.29.2` [BB-5587]

playbooks/roles/common-server-init/tasks/misc.yml, playbooks/roles/prometheus/tasks/grafana.yml, playbooks/roles/prometheus/tasks/main.yml
This PR updates the prometheus playbook to the latest version and ensures we can install Grafana correctly. Also a small issue with python alternatives linking is fixed.
1. Add `prometheus-upgrade.net.opencraft.hosting` to `hosts`
2. Copy the `prometheus.net.opencraft.hosting.yml` as `prometheus-upgrade.net.opencraft.hosting.yml`
3. Execute `ansible-playbook -vvv deploy/playbooks/prometheus.yml -l prometheus-upgrade.net.opencraft.hosting`
N/A
=> [SE-5399] Update prometheus server

playbooks/roles/sanity-checker/files/sanity_check.py
This PR fixes the sanity checker on those systems where the **default** python version is Python 3.
* See [this comment](https://tasks.opencraft.com/browse/SE-4548?focusedCommentId=243911&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-243911)
N/A
Check that the servers mentioned in the linked comment are reporting now.
ASAP
=> fix: python3 compatibility

playbooks/group_vars/prometheus/public.yml
Group prometheus alert notifications by "alertname" to bring back the old behavior before our recent prometheus upgrade.
The new version aggregates all alerts in s specified time interval by default, but we want it to split them up by alert type (aka "alertname").
**Ticket**: [SE-5457](https://tasks.opencraft.com/browse/SE-5457)
1. This change was already deployed to prometheus.
2. Verify that the `/etc/prometheus/alertmanager/alertmanager.yml` file on the prometheus server contains the correct `group_by` setting.
3. Verify that email notifications from prometheus to the ops@ mailing list received after Apr 7th, 7:00 AM UTC (when the change was deployed) are clearly separated by alert type -- you should see the alert type in the first position after the "[FIRING:N]" …
=> [SE-5457] Group prometheus alerts by alertname.

playbooks/group_vars/ocim/public.yml
Ocim uses many temporary files. Increase tmpreaper runtime since the default often isn't enough for cleaning up temporary files on Ocim.
1. I already ran ansible-playbook with this change on ocim stage & prod.
2. Verify that `/etc/tmpreaprer.conf` contains the new timeout value.
Time will tell if 180 seconds is enough.
=> Increase tmpreaper runtime for ocim

playbooks/roles/wordpress/templates/default-nginx.j2, playbooks/roles/wordpress/templates/maintenance-nginx.j2, playbooks/roles/wordpress/templates/wordpress-nginx.j2
The certbot auto-renewal script was throwing errors at renewal, on investigation we found that certbot looks for a ``well-known/acme-challenge/`` directory which was not present in the webroot so it was throwing a 404 error. On adding  the following lines in ngnix config we set the ``root`` for the URL.
**JIRA tickets**: [BB-6098](https://tasks.opencraft.com/browse/BB-6098)
~~**Discussions**: Link to any public dicussions about this PR or the design/architecture. Otherwise omit this.~~
~~**Screenshots**: Always include screenshots if there is any change to the UI.~~
~~**Sandbox URL**: TBD - sandbox is being provisioned.~~
~~**Merge deadline**: "None" if there's no rush, "ASAP" if it's critical, or provide a specific date if there is one.~~ …
=> [BB-6098] fix: Whitelisting certbot urls for certificate renewal

playbooks/roles/load-balancer-v2/defaults/main.yml
We updated haproxy to use ubuntu 20.04 so we ended up updating haproxy as well
**JIRA tickets**: [SE-5531](https://tasks.opencraft.com/browse/SE-5531)
**Discussions**: https://chat.opencraft.com/opencraft/pl/ewwz7j5gfbn5dyzznru73ud1cr
~~**Screenshots**: Always include screenshots if there is any change to the UI.~~
~~**Sandbox URL**: TBD - sandbox is being provisioned.~~
~~**Merge deadline**: "None" if there's no rush, "ASAP" if it's critical, or provide a specific date if there is one.~~
Already deployed on haproxy-b-1.net.opencraft.hosting
None
**Reviewers**
=> fix: update haproxy version

playbooks/roles/discourse/templates/app.yml.j2
This PR adds discourse-reactions plugin which allows user to add their reactions to the post. ([for more info](https://meta.discourse.org/t/discourse-reactions-beyond-likes/183261))
Link to ticket: https://tasks.opencraft.com/browse/BB-5981
- Run a [discourse docker server](https://github.com/bitnami/bitnami-docker-discourse)
- Update the app.yml file with the changes in this PR (to add the plugin and SiteSettings)
- Create a forum and try reacting to a comment.
=> feat: adds discourse reaction plugin [BB-5981]

requirements_ansible_2.8.17.txt
This PR pins the Markupsafe library's version in order for Ansible to deploy using the system Python Version 3.8.
Jinja2 doesn't have version pin on its dependency Markupsafe. Due to
this pip tries to get the latest version of Markupsafe. But Jinja2 is
pinned to 2.11.3 which depends on `soft_unicode`, which was removed from
Markupsafe in version 2.1.0. Hence, this commit pins Markupsafe to the
next lower version - 2.0.1.
- [JIRA Ticket](https://tasks.opencraft.com/browse/BB-6166)
- [Markupsafe 2.1.0 release notes](https://markupsafe.palletsprojects.com/en/2.1.x/changes/#version-2-1-0)
=> [BB-6166] Pin markupsave version in ansible 2.8.17 requirements

playbooks/roles/mail/defaults/main.yml, playbooks/roles/mail/tasks/main.yml, playbooks/roles/mail/templates/postfix-header-checks.j2, playbooks/roles/mail/templates/postfix-main.cf.j2, playbooks/roles/postfix/templates/main.cf
This PR contains a fix for the mail relay so that
it adds the correct server when communicating with Google's SMTP
server.
- Chat thread https://chat.opencraft.com/opencraft/pl/gg5swq9bujdzun9rjbix3nj5cr
- https://tasks.opencraft.com/browse/SE-5436
- https://github.com/open-craft/ansible-secrets/pull/379
- https://gitlab.com/opencraft/documentation/private/-/merge_requests/620
- Run `ansible-playbook -vvv deploy/playbooks/relay.yml -l relay.net.opencraft.hosting` [this change is already deployed]
- In the file `/etc/postfix/main.cf` there'll be a line that contains `smtp_helo_name = opencraft.com`
2 May 20221
=> fix: helo for SMTP relay server [SE-5436]

playbooks/roles/consul/tasks/main.yml
The consul directories were mounted on staging haproxy server,
hence when images are rebuild the permission for the storage is changed.
This make sures that we recursively change permission to the required
one.
**JIRA tickets**: [BB-6188](https://tasks.opencraft.com/browse/BB-6188)
**Discussions**: ~~Link to any public dicussions about this PR or the design/architecture. Otherwise omit this.~~
~~**Screenshots**: Always include screenshots if there is any change to the UI.~~
~~**Sandbox URL**: TBD - sandbox is being provisioned.~~
~~**Merge deadline**: "None" if there's no rush, "ASAP" if it's critical, or provide a specific date if there is one.~~
Check /var/lib/consul/* permission and group and user should be consul.
**Author notes and …
=> fix: Recursively add permission to all the direcrtory

playbooks/group_vars/prometheus/public.yml
We are getting many false alerts about average response time being too high.
With this tweak we ignore response times  on instances that have very few requests in the past 10 minutes.
The problem was that if an instance would only get two requests in the last 5 minutes for example, and one of the requests took around 2 seconds, the average response time was already above 1 second.
This tries to avoid alerts like these by ignoring instances that received less than 50 requests in the past 10 minutes.
- Look at the `haproxy_backend_response_time_high` on the [prometheus alerts page](https://prometheus.net.opencraft.hosting/alerts).
- Verify that the error condition looks correct.
- Verify that we've been getting less `haproxy_backend_response_time_high` alerts …
=> Tweak backend response time alert conditions.

playbooks/roles/postfix/defaults/main.yml, playbooks/roles/postfix/tasks/main.yml, playbooks/roles/postfix/templates/client-passwd.j2, playbooks/roles/postfix/templates/main.cf, playbooks/roles/postfix/templates/relay_maps.j2
We need to able to route internal emails through Gmail and
client emails through AuthSMTP.
The changes in the commit allow setting a default SMTP provider in
addition to routing to a different provider based on the sender
domain.
The changes of note are:
- Rename `POSTFIX_RELAY_HOST` to `POSTFIX_RELAY_DEFAULT_HOST`
- Removing all the internal relays because they're not needed anymore. `mail.opencraft.com` is only used for the mailing lists.
- Generating the `client-passwd` file based on a list of SMTP details instead of assuming only one is provided.
- https://tasks.opencraft.com/browse/SE-5564
See corresponding secrets PR.
=> feat: postfix role now supports multiple relays

playbooks/roles/mysql/defaults/main.yml, playbooks/roles/mysql/tasks/main.yml, playbooks/roles/mysql/templates/pinned_versions.j2
This PR contains changes to upgrade the MySQL version to the latest release in 5.7.
Debian snapshot no longer has the latest versions of mysql 5.6 ad 5.7, so the changes made here are to install the packages from Oracle.
This required a new config var `MYSQL_PINNED_VERSION` that will pin the version of MySQL installed, otherwise the built-in packages will whatever is installed.
- https://tasks.opencraft.com/browse/SE-5540
- The changes have already been deployed to the MySQL servers. Check that `apt upgrade` results in no changes to the MySQL libs even though they're listed when running `apt list --upgradeable`
```bash
ansible-playbook -vvv deploy/playbooks/mysql.yml -l [server]
```
Will deploy the changes
30 May 2022
=> fix: allow using latest mysql 5.7 version on Ubuntu 20.04

playbooks/roles/sprintcraft/defaults/main.yml, playbooks/roles/sprintcraft/meta/main.yml, playbooks/roles/sprintcraft/templates/docker-compose.yml.j2
This is a part of the cleanup from https://gitlab.com/opencraft/dev/sprintcraft/-/merge_requests/28.
Thanks to this, we can use SSL with Flower.
=> feat: use path instead of a different port for Flower in SprinCraft [BB-6393] 

playbooks/roles/postfix/tasks/main.yml
Fixes the conditional when writing relay certificates so that they don't write anything if there's no content.
In related PR.
=> fix: only write postfix certs if there's content

playbooks/roles/cert-manager/tasks/main.yml
This PR updates cert-manager to run on Ubuntu 20.04 **only**. To achieve this, cert-manager was made to work with Python3.8 in [this PR](https://github.com/open-craft/cert-manager/pull/24).
Run the playbook from the secrets repo.
`ansible-playbook -vvv deploy/playbooks/cert-manager.yml -l cert-manager-stage.net.opencraft.hosting.yml`
There should be no errors.
The changes have already been deployed to `cert-manager-stage.net.opencraft.hosting`. 
- Create a sandbox on https://stage.manage.opencraft.com 
- SSH onto the server
- Verify that your new sandbox's certificate shows up in `/etc/letsencrypt/live/` within about 5 minutes or so after creation.
=> chore: remove python3.6 and use system installed python 3.8

playbooks/roles/sanity-checker/files/sanity_check.py
@gabor-boros @keithgg We got an alert from Dead Man's Snitch that our mail server's sanity check was failing to report in. The mail queue was full _and_ it couldn't alert us about this because of this error:
```
Traceback (most recent call last):
File "/usr/local/sbin/sanity-check.py", line 225, in <module>
sanity_check(json_data)
File "/usr/local/sbin/sanity-check.py", line 195, in sanity_check
send_message(json_data['send_report_to'], json_data['subject'], report_text)
File "/usr/local/sbin/sanity-check.py", line 92, in send_message
process.communicate(body)
File "/usr/lib/python3.8/subprocess.py", line 1013, in communicate
self._stdin_write(input)
File "/usr/lib/python3.8/subprocess.py", line 962, in _stdin_write
self.stdin.write(input)
TypeError: a bytes-like object is required, not …
```
=> Fix an error in the sanity checker [MNG-3199]

playbooks/roles/postfix/defaults/main.yml, playbooks/roles/postfix/tasks/main.yml
Fixes the permissions on the dovecot directory. When a new server is deployed without this change, there'll be an error message:
```
Aug 16 12:53:08 relay dovecot: auth: Error: passwd-file(discourse,54.38.245.59): stat(/etc/dovecot/private/users) failed: Permission denied (euid=114(dovecot) egid=123(dovecot) missing +x perm: /etc/dovecot/private, dir owned by 0:0 mode=0700)
```
This PR correct the user on the directory so that it can be read.
In the secrets repo.
=> fix: permissions on dovecot directory

playbooks/roles/mail/defaults/main.yml, playbooks/roles/mail/handlers/main.yml, playbooks/roles/mail/tasks/main.yml
Fixes an issue when deploying the `mail.yml` role. `OPENCRAFT_HEADER_TOKEN` cannot be used in a `when` statement when the value is `null`.
Also adds the handler for the `postmap transport` that was missing.
I've added `mail-test.net.opencraft.hosting` in the commit https://github.com/open-craft/ansible-secrets/commit/3feae9ab01d7c85acc6274a86f49cfd35fc75299
Check out the branch `keith/fix-postfix-header-checks` here and in the secrets repo and deploy:
```bash
ansible-playbook -vvv deploy/playbooks/mail.yml -l mail-test.net.opencraft.hosting --private-key=~/.ssh/vm.pem
```
Without these changes you will get an error.
=> fix: header_checks didn't have a handler

playbooks/group_vars/ocim/public.yml, playbooks/roles/common-server-init/defaults/main.yml, playbooks/roles/common-server-init/tasks/misc.yml, playbooks/roles/common-server-init/templates/tmpreaper.conf, playbooks/roles/common-server/defaults/main.yml
We discovered that tmpreaper doesn't work well together with chkrootkit which (among other things) periodically scans contents of temporary files, thereby updating files' atime values and preventing tmpreaper from being able to purge old files based on their access timestamps.
Since the combination was never working, and we want to keep using chkrootkit, we decided to remove tmpreaper and manually clean up temporary files when disk space gets low.
Note that on the vast majority of our servers/VMs, the amount of temporary files is tiny, with one of the few exceptions being VMs that run Ocim.
**Testing**
1. Checkout this branch and run `ansible-playbook -l ocim-stage deploy/playbooks/ocim.yml --tags=common-server`
2. Verify that the playbook runs successfully, and does not install …
=> [SE-5766] Remove references to tmpreaper.

playbooks/group_vars/vault/public.yml, playbooks/roles/load-balancer-v2/defaults/main.yml, playbooks/roles/load-balancer-v2/templates/haproxy.cfg.ctmpl
1. Stats page is only available via HAProxy domains
2. Limit vault access to vault domains
This was not completely possible as `vault` terminates SSL connections itself. This meant that we have to keep the vault port open. However, the change in this PR limits access vault to only `vault` domains.
- Add HSTS headers
The changes in this PR have already been deployed to the staging haproxy servers.
WRT to issues mentioned in the description, they can be reproduced by using any domain that had been provisioned on the webserver. For testing purposes, we'll use https://oc-5456.stage.opencraft.hosting
Visit https://oc-5456.stage.opencraft.hosting:8404, you should get a connection refused error. You should be able to view the stats by going to http://haproxy-stage.net.opencraft.hosting/stats …
=> chore: ssl fixes

playbooks/roles/load-balancer-v2/templates/haproxy.cfg.ctmpl
Fixes the vault cluster communication so that nodes can reach each other.
This PR allows communication through port 8201 to go through without inspecting or changing anything. Previously we were inspecting the SSL headers to determine if the request is being sent to a vault domain. However, that breaks the cluster communication.
Regrettably, this port needs to remain open for the vault cluster to communicate effectively.
- Read through the code
- Verify that you can log in on any of the vault staging servers:
- https://vault-stage-a-1.net.opencraft.hosting:8200/
- https://vault-stage-b-1.net.opencraft.hosting:8200/
- https://vault-stage-c-1.net.opencraft.hosting:8200/
- https://vault-stage.net.opencraft.hosting:8200/
=> fix: removed ssl options from vault cluster

playbooks/roles/load-balancer-v2/defaults/main.yml, playbooks/roles/load-balancer-v2/tasks/main.yml, playbooks/roles/load-balancer-v2/templates/blacklisted-ips.j2, playbooks/roles/load-balancer-v2/templates/haproxy.cfg.ctmpl
Adds the ability to HAProxy to block abusive IPs. To configure add the relevant IP to the `haproxy_blocked_ips` array.
Run this command. It will route through `haproxy-stage-1` for `mapnutmeg.stage.opencraft.hosting` and give you the heartbeat output.
- Verify SSL works (you should get the heartbeat response)
```
curl --insecure --resolve 'mapnutmeg.stage.opencraft.hosting:443:145.239.14.5' https://mapnutmeg.stage.opencraft.hosting/heartbeat?extended
```
- Verify HTTP works (you should get a 404)
```
curl -L --resolve 'mapnutmeg.stage.opencraft.hosting:80:145.239.14.5' http://mapnutmeg.stage.opencraft.hosting/.well-known/acme-challenge/
```
Add your IP to the `haproxy_blocked_ips` array and deploy `haproxy-stage-1` (I comment out `common-server` and `node-exporter` to make it faster) …
=> feat: block abusive ips on haproxy

playbooks/roles/fluent-bit/defaults/main.yml
This PR adds an index name for fluent-bit logs to be able to identify logs easier and setup log cleanup on OpenSearch side.
=> refactor: add fluent-bit index name
