open-craft/ansible-playbooks

- requirements.yml
> Fix temporary version changes that were accidentally merged.

- playbooks/deploy-all.yml
- playbooks/group_vars/learner-profile-dashboard/public.yml
- playbooks/learner-profile-dashboard.yml
- playbooks/roles/learner-profile-dashboard/README.md
- playbooks/roles/learner-profile-dashboard/defaults/main.yml
- playbooks/roles/learner-profile-dashboard/tasks/configure_log_download.yml
- playbooks/roles/learner-profile-dashboard/tasks/configure_nginx.yml
- playbooks/roles/learner-profile-dashboard/tasks/deploy-app.yml
- playbooks/roles/learner-profile-dashboard/tasks/deploy-gunicorn.yml
- playbooks/roles/learner-profile-dashboard/tasks/log_volume.yml
- playbooks/roles/learner-profile-dashboard/tasks/main.yml
- playbooks/roles/learner-profile-dashboard/templates/logrotate.d
- playbooks/roles/learner-profile-dashboard/templates/lpd-pre-backup.sh
- playbooks/roles/learner-profile-dashboard/templates/lpd.gunicorn
- playbooks/roles/learner-profile-dashboard/templates/lpd.site
- playbooks/roles/learner-profile-dashboard/templates/lpd_settings.py
This PR adds learner-profile-dashboard for provisioning a stage server of the Learner Profile Dashboard.
cf [OC-4364](https://tasks.opencraft.com/browse/OC-4364)
The role was used to deploy https://lpd-stage.opencraft.hosting
Squashed from ddd507033c04bb42036dca853a1a66e303c29611.
> Add learner-profile-dashboard role.

- playbooks/roles/learner-profile-dashboard/templates/lpd_settings.py
cf. [OC-4614](https://tasks.opencraft.com/browse/OC-4614)
This PR goes together with https://github.com/open-craft/ansible-secrets/pull/54.
See https://github.com/open-craft/ansible-secrets/pull/54.
**Reviewers**
> Add settings for integration with adaptive engine.

- playbooks/group_vars/mongodb/public.yml
More details: https://github.com/open-craft/ansible-playbooks/pull/43#issuecomment-397143857
> Fix filebeat log path for mongodb

- playbooks/roles/mattermail/defaults/main.yml
- playbooks/roles/mattermail/templates/config.json.j2
With this, we should get the following result:
```
"MailTemplate": "@here :incoming_envelope: _From: **{{.From}}**_\n>_{{.Subject}}_",
```
I have confirmed that with running the playbook with `--diff`.
> Make a mattermail template without message and with @here.

- playbooks/consul-acl.yml
- playbooks/roles/consul-acl/README.md
- playbooks/roles/consul-acl/default/main.yml
- playbooks/roles/consul-acl/tasks/main.yml
- playbooks/roles/consul/defaults/main.yml
- playbooks/roles/consul/meta/main.yml
- playbooks/roles/consul/tasks/main.yml
- playbooks/roles/consul/templates/config.json.j2
Also add the ability to configure the anonymous token.
See https://github.com/open-craft/ansible-secrets/pull/82.
> Add playbook for Consul ACL token provisioning

- playbooks/group_vars/prometheus/public.yml
[See chat.](https://chat.opencraft.com/opencraft/pl/jn8gkqmcibnc3jijwdgepdfkrw)
> Ignore the snap mount.

- playbooks/roles/consul/templates/backup-pre-consul.sh
See https://github.com/open-craft/ansible-secrets/pull/90.
> Snapshots require master tokens.

- playbooks/roles/hxat/defaults/main.yml
Differences: https://github.com/lduarte1991/hxat/compare/v1.1.4..v1.1.5
Solves a problem with a popup, and a bug when answering to a comment which had a deleted reply.
> Minor hxat upgrade, to 1.1.5

- playbooks/roles/hxat/defaults/main.yml
Just after https://github.com/open-craft/ansible-playbooks/pull/92, a minor fix to make a popup go away.
Changes: https://github.com/lduarte1991/hxat/compare/v1.1.5..v1.1.6
> Minor hxat upgrade, to 1.1.6

- playbooks/load-balancer-v2.yml
- playbooks/roles/consul-template/README.md
- playbooks/roles/consul-template/defaults/main.yml
- playbooks/roles/consul-template/tasks/main.yml
- playbooks/roles/curator/README.md
- playbooks/roles/kibana/README.md
- playbooks/roles/load-balancer-v2/README.md
- playbooks/roles/load-balancer-v2/defaults/main.yml
- playbooks/roles/load-balancer-v2/files/backend.map.ctmpl
- playbooks/roles/load-balancer-v2/files/certs.pem.ctmpl
- playbooks/roles/load-balancer-v2/files/haproxy.cfg.ctmpl
- playbooks/roles/load-balancer-v2/meta/main.yml
- playbooks/roles/load-balancer-v2/tasks/main.yml
- playbooks/roles/load-balancer-v2/templates/backend.map.hcl.j2
- playbooks/roles/load-balancer-v2/templates/certs.pem.hcl.j2
- playbooks/roles/load-balancer-v2/templates/haproxy.cfg.hcl.j2
- playbooks/roles/load-balancer-v2/templates/nginx-maintenance.conf
- playbooks/roles/vault/tasks/main.yml
See https://github.com/open-craft/ansible-secrets/pull/103.
This only installs consul-template, and has a WIP version of lbv2, which I needed to add to actually test this somewhere live.
The lbv2 role will make use consul-template in ways described within this PR's discussion thread, in a future ticket.
> [BB-855] Install consul-template binary

- README.md
- test-requirements.txt
> fix argument inversion in README.md

- playbooks/roles/vault/tasks/main.yml
- test-requirements.txt
Based on suggestions from @pilou- It can be tested with
- pip install -r test-requirements.txt
- molecule test -s vault
> portability fixes for molecule

- molecule/vault/Dockerfile.j2
- molecule/vault/molecule.yml
- molecule/vault/tests/test_vault.py
- playbooks/roles/vault/defaults/main.yml
- playbooks/roles/vault/tasks/main.yml
- playbooks/roles/vault/templates/vault-env.j2
@UmanShahzad this should fix the regression you had [here](https://github.com/open-craft/ansible-playbooks/pull/100#discussion_r257869478)
> vault environment is for ubuntu, not root

- playbooks/group_vars/load-balancer/public.yml
- playbooks/roles/consul-template/defaults/main.yml
- playbooks/roles/load-balancer-v2/defaults/main.yml
- playbooks/roles/load-balancer-v2/files/backend.map.ctmpl
- playbooks/roles/load-balancer-v2/files/certs.pem.ctmpl
- playbooks/roles/load-balancer-v2/files/haproxy.cfg.ctmpl
- playbooks/roles/load-balancer-v2/meta/main.yml
- playbooks/roles/load-balancer-v2/tasks/exporter.yml
- playbooks/roles/load-balancer-v2/tasks/main.yml
- playbooks/roles/load-balancer-v2/tasks/maintenance.yml
- playbooks/roles/load-balancer-v2/templates/backend.map.hcl.j2
- playbooks/roles/load-balancer-v2/templates/certs.pem.hcl.j2
- playbooks/roles/load-balancer-v2/templates/consul-template-render.service
- playbooks/roles/load-balancer-v2/templates/consul-template-render.sh
- playbooks/roles/load-balancer-v2/templates/haproxy-exporter.service.j2
- playbooks/roles/load-balancer-v2/templates/haproxy.cfg.hcl.j2
See https://github.com/open-craft/ansible-secrets/pull/104.
> [BB-857] Complete the load-balancer-v2 role

- playbooks/load-balancer.yml
- playbooks/roles/unbound/defaults/main.yml
- playbooks/roles/unbound/handlers/main.yml
- playbooks/roles/unbound/tasks/main.yml
- playbooks/roles/unbound/templates/cache-and-forward.conf.j2
This will be used on haproxy-stage.
> [BB-840] Add a role to install and set up unbound

- playbooks/roles/wordpress/defaults/main.yml
- playbooks/roles/wordpress/tasks/deploy.yml
- playbooks/roles/wordpress/tasks/main.yml
- playbooks/roles/wordpress/tasks/nginx.yml
- playbooks/roles/wordpress/tasks/restore.yml
- playbooks/roles/wordpress/tasks/wordpress.yml
- playbooks/roles/wordpress/templates/wordpress-nginx.j2
- playbooks/roles/wordpress/templates/wp-config.php.j2
- playbooks/wordpress.yml
Testing instructions on https://github.com/open-craft/ansible-secrets/pull/120
> BB-1269: Update opencraft website deployment scripts [WIP]

- playbooks/roles/load-balancer-v2/tasks/main.yml
Fix small typo that prevented redeployment of load balancers.
**Reviewer:**
> BB-1474: Fix typo on load balancer v2 playbook

- playbooks/roles/curator/templates/action.yml.j2
- playbooks/roles/curator/templates/config.yml.j2
This PR sets a few configuration flags to reduce the amount of spam sent by curator.
**Reviewer: **
> BB-1466: Reduce curator verbosity to reduce spam

- playbooks/roles/load-balancer-v2/tasks/main.yml
- playbooks/roles/load-balancer-v2/templates/backend.map.ctmpl
- playbooks/roles/load-balancer-v2/templates/haproxy.cfg.ctmpl
This PR fixes a few bugs found while deploying the new highly available load balancers.
**Reviewer:**
> BB-1488: Fixes a few bugs on load balancer deployment scripts

- playbooks/deploy-all.yml
- playbooks/roles/docker-compose/README.md
- playbooks/roles/docker-compose/handlers/main.yml
- playbooks/roles/docker-compose/tasks/main.yml
- playbooks/roles/sprints/README.md
- playbooks/roles/sprints/defaults/main.yml
- playbooks/roles/sprints/files/deploy.sh
- playbooks/roles/sprints/handlers/main.yml
- playbooks/roles/sprints/tasks/main.yml
- playbooks/roles/sprints/templates/docker-compose.yml.j2
- playbooks/roles/sprints/templates/env.j2
- playbooks/sprints.yml
This is related to open-craft/sprints#6.
>  [BB-1247] Add Sprints

- playbooks/roles/ocim/defaults/main.yml
- playbooks/roles/ocim/tasks/common.yml
- playbooks/roles/ocim/templates/archived_cleanup.j2
Description
=========
This pull request adds the script `bin/archived_cleanup.sh` and a cron job to run it weekly.
The script will run the `delete_archived` management command implemented on https://github.com/open-craft/opencraft/pull/458
Testing
----------
1. Checkout this branch in the `deploy` directory of your devstack.
2. Run `vagrant provision` to rerun the provisioning.
3. Check the `bin/archived_cleanup.sh` script is present and using the correct number of months.
4. Check the cron entry is correct.
> [BB-1604] Add archived_cleanup script and cron job

- playbooks/roles/sprints/templates/docker-compose.yml.j2
This is a trivial change, so merging this.
> [BB-1320] Automicatically restart Redis in Sprints

- playbooks/roles/logstash/defaults/main.yml
- playbooks/roles/logstash/templates/logstash.conf.j2
Replaces the IP address in logs with a fingerprinted version of the same.
> [BB-1784] Update logstash filter to remove IP

- playbooks/group_vars/mongodb/public.yml
- playbooks/roles/certbot/templates/nginx-default-server.j2
- playbooks/roles/common-server-init/tasks/misc.yml
- playbooks/roles/mongodb/tasks/main.yml
More info at https://tasks.opencraft.com/browse/BB-2543
> Fix mongodb playbook issues

- playbooks/group_vars/elk/public.yml
- playbooks/roles/common-server-init/handlers/main.yml
- playbooks/roles/kibana/tasks/main.yml
- playbooks/roles/logstash/tasks/main.yml
Updated ELK playbook and roles it depends on to support ELK 7.x and Ubuntu 18.04
**JIRA tickets**: [BB-3012](https://tasks.opencraft.com/browse/BB-3012)
Check that https://logs.opencraft.com works, receives ~70k log records per day and is performant.
**Author notes and concerns**: None
**Reviewers**
> [BB-3012] ELK upgrade

- playbooks/roles/sprints/README.md
This:
1. Adds a short guide to deploying Sprints on smaller instances. This was not added to playbooks, because the approach might differ depending on the selected hosting provider (some providers offer 20GB as the lowest possible storage size, so it would not be a problem there) and a chosen instance flavor (which can be changed in case of a required redeployment).
2. Removes TODO items that have been fixed in #133.
> [BB-3156] Update Sprints README

- playbooks/roles/crafty-bot/defaults/main.yml
- playbooks/roles/crafty-bot/files/docker-compose.yml
- playbooks/roles/crafty-bot/meta/main.yml
Add new template ID variable placeholders
**Reviewers**
> [SE-3850] Add new template ID variable placeholders

- playbooks/roles/mailing-list/handlers/main.yml
- playbooks/roles/mailing-list/tasks/main.yml
- playbooks/roles/mailing-list/templates/postfix-main.cf
Basic plan for adding postfix to the mailinglist server and configuring it.
> Add local posfix configuration for mailman3

- playbooks/mailing-list.yml
- playbooks/roles/mailing-list/README.md
- playbooks/roles/mailing-list/defaults/main.yml
- playbooks/roles/mailing-list/handlers/main.yml
- playbooks/roles/mailing-list/tasks/main.yml
- playbooks/roles/mailing-list/templates/mailman-hyperkitty.cfg.j2
- playbooks/roles/mailing-list/templates/mailman-web.py.j2
- playbooks/roles/mailing-list/templates/mailman.cfg.j2
- playbooks/roles/mailing-list/templates/mailman3-nginx-proxy.conf.j2
- playbooks/roles/mailing-list/templates/postfix-main.cf.j2
[FAL-1751](https://tasks.opencraft.com/browse/FAL-1751)
Add ansible scripts for configuring a mailing list.
Work in progress.
- Set configuration variables
- Run this against an instance
- Verify that mailman3, mailman3-web, nginx proxy, postfix are all set up.
**Reviewers**:
> FAL-1751 Configure mailing list software

- playbooks/roles/kibana/defaults/main.yml
[FAL-2088](https://tasks.opencraft.com/browse/FAL-2088)
These aren't used since https://github.com/open-craft/ansible-playbooks/pull/188
- verify that these variables aren't used anywhere
**Reviewers**:
> FAL-2088 Remove unused kibana variables

- playbooks/deploy-all.yml
Update a playbook name that has been renamed earlier.
Part of https://github.com/open-craft/ansible-secrets/pull/338
**Reviewers**
- @gabor-boros
> [FAL-115] Update playbook name

- playbooks/roles/mail/defaults/main.yml
- playbooks/roles/mail/tasks/main.yml
- playbooks/roles/mail/templates/mailman-web.py.j2
- playbooks/roles/mail/templates/mailman3-nginx-proxy.conf.j2
Update mailman3 configuration to work with the latest release of mailman3 on Ubuntu 20.04.
> Update mailman configuration to match latest version of mailman on 20.04 [BB-4467]

- playbooks/roles/mail/README.md
This adds a note about patching "unknown encoding" errors in Mailman.
Jira ticket: [BB-5416](https://tasks.opencraft.com/browse/BB-5416)
> [BB-5416] Mailman patches

- playbooks/roles/backup-pruner/defaults/main.yml
- playbooks/roles/backup-pruner/tasks/main.yml
Switch to pip for tarsnapper
**JIRA tickets**: [BB-5459](https://tasks.opencraft.com/browse/BB-5459)
**Discussions**: [MM](https://chat.opencraft.com/opencraft/pl/tyhig15fg3rwmn34kjz7tfurce)
~~**Screenshots**: Always include screenshots if there is any change to the UI.~~
~~**Sandbox URL**: TBD - sandbox is being provisioned.~~
~~**Merge deadline**: "None" if there's no rush, "ASAP" if it's critical, or provide a specific date if there is one.~~
None
None
**Reviewers**
> feat: tarsnapper installed through pip 

- playbooks/roles/sprintcraft/defaults/main.yml
See [this PR](https://github.com/open-craft/ansible-secrets/pull/399).
> [BB-6197] chore: add the default value for FEATURE_AUTOMATED_SPRINT_COMPLETION variable

- playbooks/roles/ocim/README.md
- playbooks/roles/ocim/tasks/main.yml
- playbooks/roles/ocim/templates/ocim-screen.service
Updates references for the console move from Github to Gitlab
Proofread the changes to see if they make sense. 
Check if there are any references that were missed.
- https://tasks.opencraft.com/browse/SE-5008
> chore: update ocim references from github to gitlab
